export interface Testimonial {
  id: number
  name: string
  role: string
  location: string
  country: string
  rating: number
  comment: string
  initials: string
}

// Set 1 - 100 testimonials
const testimonialsSet1: Testimonial[] = [
  // USA - 40 testimonials (40%)
  { id: 1, name: "Sarah Mitchell", role: "Senior Medical Coder", location: "New York, USA", country: "USA", rating: 5, comment: "AccuCoder has completely transformed my workflow. The AI assistance is incredibly accurate and saves me hours every day.", initials: "SM" },
  { id: 2, name: "Michael Thompson", role: "Coding Supervisor", location: "California, USA", country: "USA", rating: 5, comment: "Our team's productivity has increased by 40% since implementing AccuCoder. The learning resources are exceptional.", initials: "MT" },
  { id: 3, name: "Lisa Patterson", role: "CDI Specialist", location: "Texas, USA", country: "USA", rating: 4, comment: "The CDI tools are outstanding! Quick validation and compliance checking make my job so much easier.", initials: "LP" },
  { id: 4, name: "Robert Chen", role: "Medical Coder", location: "Washington, USA", country: "USA", rating: 3, comment: "Good platform with decent search functionality. Room for improvement in customization and some features feel incomplete.", initials: "RC" },
  { id: 5, name: "Jennifer Williams", role: "Coding Manager", location: "Florida, USA", country: "USA", rating: 5, comment: "Best coding platform I've used in 15 years. The accuracy and speed are unmatched.", initials: "JW" },
  { id: 6, name: "David Martinez", role: "Medical Biller", location: "Illinois, USA", country: "USA", rating: 2, comment: "Platform has potential but encountered several bugs. Customer support could be more responsive to critical issues.", initials: "DM" },
  { id: 7, name: "Amanda Johnson", role: "Senior Coder", location: "Georgia, USA", country: "USA", rating: 4, comment: "Very intuitive interface. The AI assistant understands complex coding scenarios really well.", initials: "AJ" },
  { id: 8, name: "Christopher Lee", role: "Coding Specialist", location: "North Carolina, USA", country: "USA", rating: 5, comment: "Training new coders is so much easier with AccuCoder's integrated learning modules.", initials: "CL" },
  { id: 9, name: "Emily Davis", role: "Medical Coder", location: "Ohio, USA", country: "USA", rating: 5, comment: "The instant code lookup feature is a game-changer. No more flipping through manuals!", initials: "ED" },
  { id: 10, name: "James Wilson", role: "Coding Director", location: "Pennsylvania, USA", country: "USA", rating: 3, comment: "Decent tool overall. Needs better integration with existing systems and more robust reporting features for management.", initials: "JW" },
  { id: 11, name: "Patricia Brown", role: "CDI Coordinator", location: "Michigan, USA", country: "USA", rating: 4, comment: "Excellent tool for clinical documentation improvement. Very comprehensive and helpful for daily tasks.", initials: "PB" },
  { id: 12, name: "Daniel Garcia", role: "Medical Coder", location: "Arizona, USA", country: "USA", rating: 5, comment: "Finally, a platform that understands the complexity of medical coding!", initials: "DG" },
  { id: 13, name: "Mary Rodriguez", role: "Coding Auditor", location: "Massachusetts, USA", country: "USA", rating: 5, comment: "Audit preparation has never been this smooth. Highly recommended for audit teams.", initials: "MR" },
  { id: 14, name: "Thomas Anderson", role: "Senior Coder", location: "Virginia, USA", country: "USA", rating: 2, comment: "Expected more from this platform. Mobile app needs significant work and desktop version has performance issues.", initials: "TA" },
  { id: 15, name: "Nancy White", role: "Coding Manager", location: "Indiana, USA", country: "USA", rating: 5, comment: "Our coding accuracy improved from 92% to 98%. Outstanding results for our department!", initials: "NW" },
  { id: 16, name: "Kevin Taylor", role: "Medical Coder", location: "Missouri, USA", country: "USA", rating: 4, comment: "The AI never fails to impress with its coding suggestions. Very smart and helpful.", initials: "KT" },
  { id: 17, name: "Barbara Moore", role: "CDI Specialist", location: "Wisconsin, USA", country: "USA", rating: 5, comment: "Best investment our hospital has made in years. Everyone on the team loves it.", initials: "BM" },
  { id: 18, name: "Steven Jackson", role: "Coding Supervisor", location: "Minnesota, USA", country: "USA", rating: 3, comment: "Solid platform with good customer support. Needs more advanced features for experienced coders and better documentation.", initials: "SJ" },
  { id: 19, name: "Karen Martin", role: "Medical Coder", location: "Colorado, USA", country: "USA", rating: 5, comment: "Makes coding so much faster and more accurate. Can't imagine working without it now.", initials: "KM" },
  { id: 20, name: "Brian Thompson", role: "Senior Coder", location: "Oregon, USA", country: "USA", rating: 4, comment: "The search functionality is incredibly fast. Saves me at least 2 hours daily.", initials: "BT" },
  { id: 21, name: "Susan Harris", role: "Coding Director", location: "Connecticut, USA", country: "USA", rating: 5, comment: "Excellent ROI and team satisfaction. Our best technology decision this year.", initials: "SH" },
  { id: 22, name: "Paul Clark", role: "Medical Coder", location: "Iowa, USA", country: "USA", rating: 1, comment: "Very disappointed. System crashes frequently and lost my work multiple times. Not worth the price at current state.", initials: "PC" },
  { id: 23, name: "Dorothy Lewis", role: "CDI Nurse", location: "Nevada, USA", country: "USA", rating: 5, comment: "Perfect blend of clinical and coding knowledge. Extremely valuable for CDI work.", initials: "DL" },
  { id: 24, name: "Mark Robinson", role: "Coding Specialist", location: "Utah, USA", country: "USA", rating: 4, comment: "AccuCoder helps me stay updated with the latest coding guidelines effortlessly.", initials: "MR" },
  { id: 25, name: "Helen Walker", role: "Medical Coder", location: "Nebraska, USA", country: "USA", rating: 5, comment: "Outstanding accuracy and user-friendly interface. Highly recommend to all coders!", initials: "HW" },
  { id: 26, name: "George Hall", role: "Coding Manager", location: "Kansas, USA", country: "USA", rating: 3, comment: "Good tool overall with room for improvement. Some features need refinement and better user guides would help.", initials: "GH" },
  { id: 27, name: "Betty Allen", role: "Senior Coder", location: "Louisiana, USA", country: "USA", rating: 5, comment: "The best coding platform on the market. Period. No competition comes close.", initials: "BA" },
  { id: 28, name: "Kenneth Young", role: "Medical Coder", location: "South Carolina, USA", country: "USA", rating: 4, comment: "AccuCoder makes complex coding scenarios manageable and straightforward.", initials: "KY" },
  { id: 29, name: "Sandra King", role: "CDI Specialist", location: "Alabama, USA", country: "USA", rating: 5, comment: "Incredible platform! Our documentation quality has improved significantly.", initials: "SK" },
  { id: 30, name: "Edward Wright", role: "Coding Supervisor", location: "Kentucky, USA", country: "USA", rating: 2, comment: "Has potential but missing key features we need. Integration issues with our EHR system caused major workflow disruptions.", initials: "EW" },
  { id: 31, name: "Margaret Scott", role: "Medical Coder", location: "Oklahoma, USA", country: "USA", rating: 5, comment: "Finally found a coding tool that actually understands what coders need!", initials: "MS" },
  { id: 32, name: "Jason Green", role: "Senior Coder", location: "Arkansas, USA", country: "USA", rating: 5, comment: "The AI suggestions are spot-on. Rarely need to make corrections.", initials: "JG" },
  { id: 33, name: "Donna Baker", role: "Coding Director", location: "Mississippi, USA", country: "USA", rating: 4, comment: "Best decision for our coding department. Results speak for themselves.", initials: "DB" },
  { id: 34, name: "Raymond Adams", role: "Medical Coder", location: "New Mexico, USA", country: "USA", rating: 3, comment: "Average experience. Platform works but nothing exceptional. Could use more keyboard shortcuts and customization options.", initials: "RA" },
  { id: 35, name: "Carol Nelson", role: "CDI Coordinator", location: "West Virginia, USA", country: "USA", rating: 5, comment: "Exceptional quality and reliability. Our go-to coding solution for everything.", initials: "CN" },
  { id: 36, name: "Frank Carter", role: "Coding Specialist", location: "Montana, USA", country: "USA", rating: 5, comment: "AccuCoder is incredibly intuitive. New coders love how easy it is to learn.", initials: "FC" },
  { id: 37, name: "Ruth Mitchell", role: "Medical Coder", location: "Delaware, USA", country: "USA", rating: 4, comment: "The platform has exceeded most of my expectations. Very solid tool overall.", initials: "RM" },
  { id: 38, name: "Jeffrey Perez", role: "Senior Coder", location: "South Dakota, USA", country: "USA", rating: 5, comment: "Great features and solid performance. Looking forward to new updates and features.", initials: "JP" },
  { id: 39, name: "Michelle Roberts", role: "Coding Manager", location: "Alaska, USA", country: "USA", rating: 5, comment: "Our team productivity increased dramatically. Best tool investment we've made.", initials: "MR" },
  { id: 40, name: "Gary Turner", role: "Medical Coder", location: "Vermont, USA", country: "USA", rating: 1, comment: "Not satisfied at all. Too many technical issues and the learning curve is steeper than advertised. Support was unhelpful.", initials: "GT" },

  // India - 30 testimonials (30%)
  { id: 41, name: "Priya Sharma", role: "Medical Coding Specialist", location: "Mumbai, India", country: "India", rating: 5, comment: "AccuCoder is simply amazing! It has made coding so much easier and faster. Best tool for Indian coders.", initials: "PS" },
  { id: 42, name: "Rajesh Kumar", role: "Senior Medical Coder", location: "Bangalore, India", country: "India", rating: 5, comment: "Bahut accha platform hai! The AI is very intelligent and understands complex cases perfectly.", initials: "RK" },
  { id: 43, name: "Anjali Patel", role: "Coding Team Lead", location: "Pune, India", country: "India", rating: 4, comment: "Great tool for our team. Productivity badh gaya significantly. Would recommend to everyone!", initials: "AP" },
  { id: 44, name: "Vikram Singh", role: "Medical Coder", location: "Hyderabad, India", country: "India", rating: 5, comment: "Perfect platform for medical coding. Training naye coders ko is very easy now. Excellent!", initials: "VS" },
  { id: 45, name: "Deepika Reddy", role: "CDI Specialist", location: "Chennai, India", country: "India", rating: 3, comment: "Decent tool but some features need improvement. Integration with Indian systems could be better. Thoda aur work required.", initials: "DR" },
  { id: 46, name: "Amit Verma", role: "Coding Supervisor", location: "Delhi, India", country: "India", rating: 5, comment: "Ekdum mast hai! The search speed is incredible. Our team loves AccuCoder.", initials: "AV" },
  { id: 47, name: "Sneha Joshi", role: "Medical Coder", location: "Ahmedabad, India", country: "India", rating: 4, comment: "Very helpful for daily coding. Kuch minor improvements needed but overall fantastic platform.", initials: "SJ" },
  { id: 48, name: "Arjun Nair", role: "Senior Coder", location: "Kochi, India", country: "India", rating: 5, comment: "AccuCoder has changed the game for us. Speed aur accuracy dono perfect hai!", initials: "AN" },
  { id: 49, name: "Kavita Desai", role: "Coding Manager", location: "Surat, India", country: "India", rating: 5, comment: "Our coding department's performance improved by 40%. Highly recommend this platform!", initials: "KD" },
  { id: 50, name: "Rahul Gupta", role: "Medical Coder", location: "Jaipur, India", country: "India", rating: 2, comment: "Not meeting expectations. Too many bugs aur customer support response time is slow. Price ke hisaab se better expected.", initials: "RG" },
  { id: 51, name: "Pooja Iyer", role: "CDI Coordinator", location: "Bangalore, India", country: "India", rating: 5, comment: "Excellent platform with amazing features. CDI work has become so much easier!", initials: "PI" },
  { id: 52, name: "Sanjay Mehta", role: "Coding Specialist", location: "Mumbai, India", country: "India", rating: 4, comment: "Very good platform. User-friendly interface aur fast search. Great for our team.", initials: "SM" },
  { id: 53, name: "Meera Rao", role: "Medical Coder", location: "Pune, India", country: "India", rating: 5, comment: "Best coding assistant ever! AI is super smart and helpful. Highly recommended!", initials: "MR" },
  { id: 54, name: "Karthik Pillai", role: "Senior Coder", location: "Hyderabad, India", country: "India", rating: 3, comment: "Okay platform with average performance. Kuch advanced features missing hai jo competitors mein available hai. Needs work.", initials: "KP" },
  { id: 55, name: "Divya Shah", role: "Coding Team Lead", location: "Chennai, India", country: "India", rating: 5, comment: "Perfect tool for managing coding team. Everyone loves it. Bahut sahi hai!", initials: "DS" },
  { id: 56, name: "Manish Jain", role: "Medical Coder", location: "Delhi, India", country: "India", rating: 4, comment: "Very helpful and efficient. Some features mein improvement chahiye but overall excellent.", initials: "MJ" },
  { id: 57, name: "Shruti Kulkarni", role: "CDI Specialist", location: "Ahmedabad, India", country: "India", rating: 5, comment: "AccuCoder is a game-changer! Documentation quality has improved significantly.", initials: "SK" },
  { id: 58, name: "Aditya Bhatt", role: "Coding Supervisor", location: "Kochi, India", country: "India", rating: 5, comment: "Excellent platform with great support. Our coding accuracy is now 98%!", initials: "AB" },
  { id: 59, name: "Neha Malhotra", role: "Medical Coder", location: "Surat, India", country: "India", rating: 2, comment: "Disappointed with performance. System lags frequently and some features don't work properly. Not worth the investment currently.", initials: "NM" },
  { id: 60, name: "Varun Kapoor", role: "Senior Coder", location: "Jaipur, India", country: "India", rating: 5, comment: "AccuCoder is simply the best! Fast, accurate, and very user-friendly. Love it!", initials: "VK" },
  { id: 61, name: "Ritika Saxena", role: "Coding Manager", location: "Bangalore, India", country: "India", rating: 4, comment: "Outstanding results for our team. Productivity aur accuracy both improved dramatically!", initials: "RS" },
  { id: 62, name: "Nikhil Agarwal", role: "Medical Coder", location: "Mumbai, India", country: "India", rating: 3, comment: "Average platform. AI assistance is good but interface could be better. Kuch features confusing hai for new users.", initials: "NA" },
  { id: 63, name: "Ishita Bansal", role: "CDI Specialist", location: "Pune, India", country: "India", rating: 5, comment: "Perfect for CDI work! Makes documentation review so much easier and faster.", initials: "IB" },
  { id: 64, name: "Rohan Chopra", role: "Coding Specialist", location: "Hyderabad, India", country: "India", rating: 5, comment: "AccuCoder is amazing! Coding speed badh gaya and errors kam ho gaye. Highly recommend!", initials: "RC" },
  { id: 65, name: "Sakshi Pandey", role: "Medical Coder", location: "Chennai, India", country: "India", rating: 4, comment: "Best coding platform available! Easy to use aur very accurate. Love AccuCoder!", initials: "SP" },
  { id: 66, name: "Akash Verma", role: "Senior Coder", location: "Delhi, India", country: "India", rating: 5, comment: "Bahut helpful tool hai. Time bachta hai aur accuracy bhi improve hui. Team ko bahut pasand hai!", initials: "AV" },
  { id: 67, name: "Riya Kapoor", role: "Coding Manager", location: "Ahmedabad, India", country: "India", rating: 1, comment: "Very poor experience. Technical glitches daily and support team doesn't respond quickly. Waste of money at current state.", initials: "RK" },
  { id: 68, name: "Suresh Nair", role: "Medical Coder", location: "Kochi, India", country: "India", rating: 5, comment: "Excellent tool for medical coders. Makes work easier aur faster. Highly recommended!", initials: "SN" },
  { id: 69, name: "Ananya Gupta", role: "CDI Specialist", location: "Surat, India", country: "India", rating: 3, comment: "Satisfactory platform. Works fine for basic tasks but advanced features need improvement. Price thoda high hai for what it offers.", initials: "AG" },
  { id: 70, name: "Rohit Sharma", role: "Coding Specialist", location: "Jaipur, India", country: "India", rating: 5, comment: "AccuCoder is the best! Bahut easy to use aur very powerful. Our team productivity has doubled!", initials: "RS" },

  // UAE - 15 testimonials (15%)
  { id: 71, name: "Ahmed Al-Rashid", role: "Medical Coding Manager", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Excellent platform for our healthcare facility. The accuracy and speed are outstanding!", initials: "AA" },
  { id: 72, name: "Fatima Hassan", role: "Senior Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "AccuCoder has transformed our coding department. Best tool in the Middle East market!", initials: "FH" },
  { id: 73, name: "Mohammed Khan", role: "CDI Specialist", location: "Dubai, UAE", country: "UAE", rating: 4, comment: "Very efficient and reliable platform. Great for multi-national healthcare facilities.", initials: "MK" },
  { id: 74, name: "Sarah Al-Mansoori", role: "Coding Supervisor", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Outstanding quality and support! Our team productivity increased significantly.", initials: "SA" },
  { id: 75, name: "Khalid Rashid", role: "Medical Coder", location: "Dubai, UAE", country: "UAE", rating: 3, comment: "Good platform but needs better support for Arabic documentation. Some features could be more intuitive.", initials: "KR" },
  { id: 76, name: "Layla Ibrahim", role: "Coding Manager", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Best coding solution we've implemented. Our accuracy rate has improved tremendously.", initials: "LI" },
  { id: 77, name: "Omar Abdullah", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 4, comment: "Very good platform with excellent AI capabilities. Minor improvements needed in regional customization.", initials: "OA" },
  { id: 78, name: "Aisha Mohamed", role: "CDI Specialist", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Perfect for our multi-cultural team. Easy to use and very accurate in coding suggestions.", initials: "AM" },
  { id: 79, name: "Hassan Ali", role: "Coding Specialist", location: "Dubai, UAE", country: "UAE", rating: 2, comment: "Expected more for the price. System has connectivity issues and lacks some essential features for our region.", initials: "HA" },
  { id: 80, name: "Mariam Khalifa", role: "Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Exceptional platform! Makes our coding work so much easier and more efficient.", initials: "MK" },
  { id: 81, name: "Abdullah Saeed", role: "Coding Director", location: "Dubai, UAE", country: "UAE", rating: 4, comment: "Solid platform with good ROI. Training resources could be better tailored to Middle East healthcare systems.", initials: "AS" },
  { id: 82, name: "Noor Ahmad", role: "Senior Coder", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Outstanding tool for medical coding. Our team loves the intuitive interface and accuracy.", initials: "NA" },
  { id: 83, name: "Yusuf Hassan", role: "CDI Coordinator", location: "Dubai, UAE", country: "UAE", rating: 3, comment: "Satisfactory performance. Works well for standard cases but struggles with complex regional coding requirements.", initials: "YH" },
  { id: 84, name: "Huda Salem", role: "Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Excellent coding assistant! Very helpful for our busy department. Highly recommend for UAE facilities.", initials: "HS" },
  { id: 85, name: "Tariq Mansoor", role: "Coding Supervisor", location: "Dubai, UAE", country: "UAE", rating: 1, comment: "Poor experience overall. Too many bugs and platform crashes during peak hours. Support response is inadequate for critical issues.", initials: "TM" },

  // Others - 15 testimonials (15%)
  { id: 86, name: "David O'Connor", role: "Medical Coder", location: "London, UK", country: "UK", rating: 5, comment: "Brilliant platform! Works perfectly for international medical coding standards. Highly recommended!", initials: "DO" },
  { id: 87, name: "Emma Wilson", role: "Senior Coder", location: "Manchester, UK", country: "UK", rating: 4, comment: "Very good platform with excellent accuracy. Integration with NHS systems could be improved.", initials: "EW" },
  { id: 88, name: "James Smith", role: "Coding Manager", location: "Birmingham, UK", country: "UK", rating: 5, comment: "Outstanding tool for our coding department. Productivity has increased significantly.", initials: "JS" },
  { id: 89, name: "Sophie Taylor", role: "CDI Specialist", location: "Edinburgh, Scotland", country: "UK", rating: 3, comment: "Decent platform but needs better support for UK-specific coding requirements. Some features feel US-centric.", initials: "ST" },
  { id: 90, name: "Michael Chen", role: "Medical Coder", location: "Toronto, Canada", country: "Canada", rating: 5, comment: "Excellent coding platform! Works perfectly with Canadian healthcare system. Very impressed.", initials: "MC" },
  { id: 91, name: "Isabella Rodriguez", role: "Senior Coder", location: "Vancouver, Canada", country: "Canada", rating: 4, comment: "Very helpful tool for medical coding. Minor adjustments needed for provincial variations.", initials: "IR" },
  { id: 92, name: "Lucas Brown", role: "Coding Supervisor", location: "Melbourne, Australia", country: "Australia", rating: 5, comment: "Outstanding platform! Our team productivity doubled since implementation. Best investment!", initials: "LB" },
  { id: 93, name: "Olivia Anderson", role: "Medical Coder", location: "Sydney, Australia", country: "Australia", rating: 2, comment: "Disappointed with Australian coding standards support. Platform seems optimized for US market only. Needs work.", initials: "OA" },
  { id: 94, name: "Liam Murphy", role: "CDI Specialist", location: "Dublin, Ireland", country: "Ireland", rating: 5, comment: "Fantastic tool for CDI work! Very accurate and easy to use. Highly recommend for Irish facilities.", initials: "LM" },
  { id: 95, name: "Sophia Martinez", role: "Coding Manager", location: "Singapore", country: "Singapore", rating: 4, comment: "Very good platform for our multi-national facility. Support team is responsive and helpful.", initials: "SM" },
  { id: 96, name: "Hans Mueller", role: "Medical Coder", location: "Berlin, Germany", country: "Germany", rating: 3, comment: "Satisfactory performance. Good for basic coding but lacks advanced features for European healthcare systems.", initials: "HM" },
  { id: 97, name: "Marie Dubois", role: "Senior Coder", location: "Paris, France", country: "France", rating: 5, comment: "Excellent platform! Very helpful for international medical coding. Our team loves it.", initials: "MD" },
  { id: 98, name: "Carlos Silva", role: "Coding Specialist", location: "São Paulo, Brazil", country: "Brazil", rating: 4, comment: "Very good tool with excellent AI. Portuguese language support could be better but overall great.", initials: "CS" },
  { id: 99, name: "Yuki Tanaka", role: "Medical Coder", location: "Tokyo, Japan", country: "Japan", rating: 1, comment: "Very poor experience. Platform not suitable for Japanese healthcare system. No local language support and cultural adaptation missing.", initials: "YT" },
  { id: 100, name: "Anna Kowalski", role: "CDI Specialist", location: "Warsaw, Poland", country: "Poland", rating: 5, comment: "Outstanding platform for CDI work! Very accurate and efficient. Best tool for European coders!", initials: "AK" },
]

// Set 2 - 100 testimonials (Different names, same distribution)
const testimonialsSet2: Testimonial[] = [
  // USA - 40 (40%)
  { id: 101, name: "Jessica Parker", role: "Medical Coder", location: "Boston, USA", country: "USA", rating: 5, comment: "AccuCoder streamlined our entire workflow. The code suggestions are incredibly accurate!", initials: "JP" },
  { id: 102, name: "Ryan Cooper", role: "Coding Director", location: "Seattle, USA", country: "USA", rating: 4, comment: "Great platform for managing large coding teams. Dashboard features are very helpful.", initials: "RC" },
  { id: 103, name: "Michelle Bennett", role: "Senior Coder", location: "Miami, USA", country: "USA", rating: 5, comment: "Best medical coding tool I've ever used. The learning curve is minimal!", initials: "MB" },
  { id: 104, name: "Andrew Foster", role: "CDI Specialist", location: "Portland, USA", country: "USA", rating: 3, comment: "Decent platform but could use more advanced analytics features. Works fine for basic needs.", initials: "AF" },
  { id: 105, name: "Rachel Coleman", role: "Coding Manager", location: "Houston, USA", country: "USA", rating: 5, comment: "Our efficiency improved by 50%! Team loves the intuitive design.", initials: "RC" },
  { id: 106, name: "Brandon Hughes", role: "Medical Coder", location: "Phoenix, USA", country: "USA", rating: 2, comment: "Too many glitches and slow load times. Expected better performance for the cost.", initials: "BH" },
  { id: 107, name: "Natalie Ross", role: "Senior Coder", location: "Philadelphia, USA", country: "USA", rating: 4, comment: "Very solid tool. AI recommendations save me hours each week.", initials: "NR" },
  { id: 108, name: "Justin Perry", role: "Coding Specialist", location: "San Antonio, USA", country: "USA", rating: 5, comment: "Perfect for complex coding scenarios. Handles edge cases beautifully.", initials: "JP" },
  { id: 109, name: "Melissa Barnes", role: "CDI Coordinator", location: "San Diego, USA", country: "USA", rating: 5, comment: "Documentation quality improved dramatically. Outstanding platform!", initials: "MB" },
  { id: 110, name: "Derek Powell", role: "Medical Coder", location: "Dallas, USA", country: "USA", rating: 3, comment: "Average experience. Some features work great, others need improvement.", initials: "DP" },
  { id: 111, name: "Stephanie Russell", role: "Coding Supervisor", location: "San Jose, USA", country: "USA", rating: 4, comment: "Good platform for team collaboration. Minor issues but overall satisfied.", initials: "SR" },
  { id: 112, name: "Trevor Sanders", role: "Senior Coder", location: "Jacksonville, USA", country: "USA", rating: 5, comment: "Exceptional accuracy! Rarely need to correct the AI suggestions.", initials: "TS" },
  { id: 113, name: "Monica Griffin", role: "Coding Manager", location: "Columbus, USA", country: "USA", rating: 5, comment: "Best investment we made this year. ROI was immediate.", initials: "MG" },
  { id: 114, name: "Gregory Bryant", role: "Medical Coder", location: "Fort Worth, USA", country: "USA", rating: 2, comment: "Disappointed with customer support response times. Platform needs bug fixes.", initials: "GB" },
  { id: 115, name: "Vanessa Hayes", role: "CDI Specialist", location: "Charlotte, USA", country: "USA", rating: 5, comment: "Perfect for CDI reviews! Makes complex documentation simple.", initials: "VH" },
  { id: 116, name: "Keith Watson", role: "Coding Director", location: "Indianapolis, USA", country: "USA", rating: 4, comment: "Solid platform with room for growth. Looking forward to future updates.", initials: "KW" },
  { id: 117, name: "Brittany Fisher", role: "Senior Coder", location: "Austin, USA", country: "USA", rating: 5, comment: "Love the interface! Clean, fast, and incredibly intuitive.", initials: "BF" },
  { id: 118, name: "Marcus Henderson", role: "Medical Coder", location: "San Francisco, USA", country: "USA", rating: 3, comment: "Works well but missing some advanced features competitors have. Good for beginners.", initials: "MH" },
  { id: 119, name: "Kristen Mason", role: "Coding Specialist", location: "Memphis, USA", country: "USA", rating: 5, comment: "Fantastic tool! Training new staff is now a breeze.", initials: "KM" },
  { id: 120, name: "Dylan Porter", role: "CDI Coordinator", location: "Detroit, USA", country: "USA", rating: 4, comment: "Very helpful for documentation improvement. Minor UI tweaks needed.", initials: "DP" },
  { id: 121, name: "Lauren Gibson", role: "Coding Manager", location: "El Paso, USA", country: "USA", rating: 5, comment: "Our accuracy rate hit 99%! Incredible results.", initials: "LG" },
  { id: 122, name: "Cameron Reynolds", role: "Senior Coder", location: "Nashville, USA", country: "USA", rating: 1, comment: "System crashes frequently. Lost work multiple times. Very frustrating experience.", initials: "CR" },
  { id: 123, name: "Amber Hunter", role: "Medical Coder", location: "Baltimore, USA", country: "USA", rating: 5, comment: "Best coding assistant ever! Makes my job so much easier.", initials: "AH" },
  { id: 124, name: "Travis Armstrong", role: "Coding Specialist", location: "Louisville, USA", country: "USA", rating: 4, comment: "Great for daily coding work. Search function is lightning fast.", initials: "TA" },
  { id: 125, name: "Crystal Spencer", role: "CDI Specialist", location: "Milwaukee, USA", country: "USA", rating: 5, comment: "Outstanding CDI tools! Query management is superb.", initials: "CS" },
  { id: 126, name: "Blake Morrison", role: "Coding Director", location: "Albuquerque, USA", country: "USA", rating: 3, comment: "Satisfactory overall. Needs better reporting capabilities for management.", initials: "BM" },
  { id: 127, name: "Miranda Graham", role: "Medical Coder", location: "Tucson, USA", country: "USA", rating: 5, comment: "Perfect balance of power and simplicity. Highly recommend!", initials: "MG" },
  { id: 128, name: "Garrett Wells", role: "Senior Coder", location: "Fresno, USA", country: "USA", rating: 4, comment: "Very good platform. Integration options could be expanded.", initials: "GW" },
  { id: 129, name: "Heather Dixon", role: "Coding Manager", location: "Mesa, USA", country: "USA", rating: 5, comment: "Team productivity soared! Everyone adapted quickly.", initials: "HD" },
  { id: 130, name: "Seth Bradley", role: "CDI Coordinator", location: "Sacramento, USA", country: "USA", rating: 2, comment: "Too expensive for what it offers. Better free alternatives available.", initials: "SB" },
  { id: 131, name: "Whitney Owens", role: "Medical Coder", location: "Atlanta, USA", country: "USA", rating: 5, comment: "Incredible AI capabilities! Understands context perfectly.", initials: "WO" },
  { id: 132, name: "Clayton Webster", role: "Coding Specialist", location: "Kansas City, USA", country: "USA", rating: 4, comment: "Solid performer with great accuracy. Minor lag issues occasionally.", initials: "CW" },
  { id: 133, name: "Tiffany Fleming", role: "Senior Coder", location: "Long Beach, USA", country: "USA", rating: 5, comment: "Best purchase decision ever! Saves me 3+ hours daily.", initials: "TF" },
  { id: 134, name: "Malcolm Mendoza", role: "Coding Director", location: "Oakland, USA", country: "USA", rating: 3, comment: "Good but not great. Waiting for promised features to be delivered.", initials: "MM" },
  { id: 135, name: "Chelsea Norman", role: "CDI Specialist", location: "Minneapolis, USA", country: "USA", rating: 5, comment: "CDI work has never been easier! Love this platform.", initials: "CN" },
  { id: 136, name: "Dustin Rice", role: "Medical Coder", location: "Tulsa, USA", country: "USA", rating: 4, comment: "Very helpful tool with excellent search capabilities.", initials: "DR" },
  { id: 137, name: "April Lynch", role: "Coding Manager", location: "Arlington, USA", country: "USA", rating: 5, comment: "Our department transformed! Accuracy and speed both improved.", initials: "AL" },
  { id: 138, name: "Wesley Hicks", role: "Senior Coder", location: "New Orleans, USA", country: "USA", rating: 1, comment: "Constant technical issues. Support is unresponsive. Very disappointed.", initials: "WH" },
  { id: 139, name: "Courtney Chapman", role: "CDI Coordinator", location: "Wichita, USA", country: "USA", rating: 5, comment: "Perfect for comprehensive documentation reviews!", initials: "CC" },
  { id: 140, name: "Spencer Walsh", role: "Medical Coder", location: "Tampa, USA", country: "USA", rating: 4, comment: "Great platform overall. Minor improvements would make it perfect.", initials: "SW" },
  
  // India - 30 (30%)
  { id: 141, name: "Aditi Verma", role: "Medical Coder", location: "Mumbai, India", country: "India", rating: 5, comment: "Ekdum zabardast! Best coding platform for Indian professionals.", initials: "AV" },
  { id: 142, name: "Kiran Patel", role: "Senior Coder", location: "Delhi, India", country: "India", rating: 4, comment: "Bahut accha hai! Makes coding work much easier and faster.", initials: "KP" },
  { id: 143, name: "Sunita Sharma", role: "Coding Manager", location: "Bangalore, India", country: "India", rating: 5, comment: "Outstanding tool! Team ki productivity badh gayi significantly.", initials: "SS" },
  { id: 144, name: "Ravi Kumar", role: "Medical Coder", location: "Hyderabad, India", country: "India", rating: 3, comment: "Theek hai but some Indian specific features missing. Improvement needed.", initials: "RK" },
  { id: 145, name: "Nisha Gupta", role: "CDI Specialist", location: "Pune, India", country: "India", rating: 5, comment: "Perfect for CDI work! Very accurate aur easy to use.", initials: "NG" },
  { id: 146, name: "Manoj Singh", role: "Coding Specialist", location: "Chennai, India", country: "India", rating: 2, comment: "Not satisfied. Bahut saari technical problems hai. Support response slow.", initials: "MS" },
  { id: 147, name: "Pooja Reddy", role: "Senior Coder", location: "Ahmedabad, India", country: "India", rating: 4, comment: "Very good platform. AI is smart aur helpful for complex cases.", initials: "PR" },
  { id: 148, name: "Vivek Joshi", role: "Coding Manager", location: "Surat, India", country: "India", rating: 5, comment: "Best investment! Our team loves it. Sab kuch smooth hai.", initials: "VJ" },
  { id: 149, name: "Swati Desai", role: "Medical Coder", location: "Jaipur, India", country: "India", rating: 5, comment: "Kamaal ka platform! Makes work so easy and efficient.", initials: "SD" },
  { id: 150, name: "Arjun Nair", role: "CDI Coordinator", location: "Kochi, India", country: "India", rating: 3, comment: "Satisfactory performance. Kuch features improve karne padenge.", initials: "AN" },
  { id: 151, name: "Deepa Iyer", role: "Coding Specialist", location: "Lucknow, India", country: "India", rating: 5, comment: "Excellent tool! Coding speed badh gaya aur errors kam hui.", initials: "DI" },
  { id: 152, name: "Sandeep Mehta", role: "Senior Coder", location: "Nagpur, India", country: "India", rating: 4, comment: "Very helpful platform. Customer support bhi accha hai.", initials: "SM" },
  { id: 153, name: "Rekha Pillai", role: "Medical Coder", location: "Indore, India", country: "India", rating: 5, comment: "Best coding assistant! AI bahut smart hai.", initials: "RP" },
  { id: 154, name: "Arun Kapoor", role: "Coding Director", location: "Bhopal, India", country: "India", rating: 2, comment: "Disappointed. Platform me bahut bugs hai. Price ke hisaab se better expected.", initials: "AK" },
  { id: 155, name: "Anita Shah", role: "CDI Specialist", location: "Vadodara, India", country: "India", rating: 5, comment: "Perfect for documentation work! Very accurate and fast.", initials: "AS" },
  { id: 156, name: "Suresh Rao", role: "Coding Manager", location: "Coimbatore, India", country: "India", rating: 4, comment: "Good platform overall. Team satisfaction high hai.", initials: "SR" },
  { id: 157, name: "Geeta Bansal", role: "Medical Coder", location: "Chandigarh, India", country: "India", rating: 5, comment: "Bahut helpful! Work ko simple bana diya.", initials: "GB" },
  { id: 158, name: "Ramesh Agarwal", role: "Senior Coder", location: "Visakhapatnam, India", country: "India", rating: 3, comment: "Average platform. Kuch advanced features missing jo chahiye.", initials: "RA" },
  { id: 159, name: "Kavita Kulkarni", role: "CDI Coordinator", location: "Nashik, India", country: "India", rating: 5, comment: "Outstanding CDI tools! Documentation quality improve hui.", initials: "KK" },
  { id: 160, name: "Prakash Pandey", role: "Coding Specialist", location: "Kanpur, India", country: "India", rating: 4, comment: "Very good tool. Search function bahut fast hai.", initials: "PP" },
  { id: 161, name: "Madhuri Deshmukh", role: "Medical Coder", location: "Aurangabad, India", country: "India", rating: 5, comment: "Excellent platform! Makes coding enjoyable.", initials: "MD" },
  { id: 162, name: "Ajay Saxena", role: "Coding Manager", location: "Gurgaon, India", country: "India", rating: 1, comment: "Very poor experience. System crash hota rehta hai. Support team ne help nahi ki.", initials: "AS" },
  { id: 163, name: "Priyanka Mishra", role: "CDI Specialist", location: "Noida, India", country: "India", rating: 5, comment: "Perfect tool! CDI work bahut easy ho gaya.", initials: "PM" },
  { id: 164, name: "Vijay Tiwari", role: "Senior Coder", location: "Patna, India", country: "India", rating: 4, comment: "Good platform with solid features. Minor improvements needed.", initials: "VT" },
  { id: 165, name: "Sneha Bhatt", role: "Medical Coder", location: "Rajkot, India", country: "India", rating: 5, comment: "Best coding tool! Sab kuch perfect hai.", initials: "SB" },
  { id: 166, name: "Harish Malhotra", role: "Coding Specialist", location: "Agra, India", country: "India", rating: 3, comment: "Theek hai but pricing thoda high. Value for money improve karo.", initials: "HM" },
  { id: 167, name: "Divya Chopra", role: "CDI Coordinator", location: "Meerut, India", country: "India", rating: 5, comment: "Excellent for documentation reviews! Very comprehensive.", initials: "DC" },
  { id: 168, name: "Sanjay Bhardwaj", role: "Coding Director", location: "Varanasi, India", country: "India", rating: 4, comment: "Good ROI. Team satisfaction high aur productivity badhi.", initials: "SB" },
  { id: 169, name: "Rupali Singh", role: "Medical Coder", location: "Amritsar, India", country: "India", rating: 5, comment: "Zabardast platform! Coding work bahut easy ho gaya.", initials: "RS" },
  { id: 170, name: "Dinesh Kumar", role: "Senior Coder", location: "Allahabad, India", country: "India", rating: 2, comment: "Not happy. Technical issues too much. Better alternatives available.", initials: "DK" },

  // UAE - 15 (15%)
  { id: 171, name: "Ali Hassan", role: "Medical Coder", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Excellent platform for UAE healthcare facilities. Very professional!", initials: "AH" },
  { id: 172, name: "Salma Ahmed", role: "Coding Manager", location: "Abu Dhabi, UAE", country: "UAE", rating: 4, comment: "Great tool for our department. Team productivity improved significantly.", initials: "SA" },
  { id: 173, name: "Khalid Rahman", role: "CDI Specialist", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Perfect for clinical documentation. Very accurate and efficient.", initials: "KR" },
  { id: 174, name: "Noura Al-Said", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 3, comment: "Satisfactory performance. Needs better regional customization for Middle East.", initials: "NA" },
  { id: 175, name: "Ibrahim Mansour", role: "Coding Specialist", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Outstanding accuracy! Best coding tool in UAE market.", initials: "IM" },
  { id: 176, name: "Fatima Yousef", role: "Medical Coder", location: "Ajman, UAE", country: "UAE", rating: 2, comment: "Expected better. Platform has issues with Arabic documentation support.", initials: "FY" },
  { id: 177, name: "Mohammed Zayed", role: "Coding Director", location: "Dubai, UAE", country: "UAE", rating: 4, comment: "Good investment for our facility. Team satisfaction is high.", initials: "MZ" },
  { id: 178, name: "Aya Khalil", role: "CDI Coordinator", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Excellent CDI tools! Makes complex reviews simple.", initials: "AK" },
  { id: 179, name: "Omar Farid", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Best coding platform we've used. Very professional and reliable.", initials: "OF" },
  { id: 180, name: "Huda Nasser", role: "Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 3, comment: "Average experience. Some features work well, others need improvement.", initials: "HN" },
  { id: 181, name: "Rashid Ali", role: "Coding Manager", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Perfect for multi-national teams. Everyone can use it effectively.", initials: "RA" },
  { id: 182, name: "Mariam Saeed", role: "CDI Specialist", location: "Sharjah, UAE", country: "UAE", rating: 4, comment: "Very helpful tool. Documentation quality improved noticeably.", initials: "MS" },
  { id: 183, name: "Hassan Ibrahim", role: "Coding Specialist", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Exceptional platform! AI is very intelligent and accurate.", initials: "HI" },
  { id: 184, name: "Laila Ahmad", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 1, comment: "Very disappointed. System crashes often and support is unhelpful. Not recommended.", initials: "LA" },
  { id: 185, name: "Tariq Hussein", role: "Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Outstanding tool! Makes coding work efficient and enjoyable.", initials: "TH" },

  // Others - 15 (15%)
  { id: 186, name: "Oliver Thompson", role: "Medical Coder", location: "London, UK", country: "UK", rating: 5, comment: "Brilliant tool! Works perfectly with NHS coding standards.", initials: "OT" },
  { id: 187, name: "Charlotte Davies", role: "Senior Coder", location: "Birmingham, UK", country: "UK", rating: 4, comment: "Very good platform. Integration with UK systems could be better.", initials: "CD" },
  { id: 188, name: "Ethan Campbell", role: "Coding Manager", location: "Toronto, Canada", country: "Canada", rating: 5, comment: "Excellent for Canadian healthcare! Team loves it.", initials: "EC" },
  { id: 189, name: "Ava Mitchell", role: "CDI Specialist", location: "Vancouver, Canada", country: "Canada", rating: 3, comment: "Satisfactory. Works fine but missing some provincial specific features.", initials: "AM" },
  { id: 190, name: "Noah Roberts", role: "Medical Coder", location: "Melbourne, Australia", country: "Australia", rating: 5, comment: "Outstanding platform! Perfect for Australian coding standards.", initials: "NR" },
  { id: 191, name: "Mia Anderson", role: "Senior Coder", location: "Sydney, Australia", country: "Australia", rating: 2, comment: "Disappointed. Too US-centric, needs better Australian market support.", initials: "MA" },
  { id: 192, name: "William Wright", role: "Coding Specialist", location: "Dublin, Ireland", country: "Ireland", rating: 4, comment: "Very helpful tool. Makes daily coding work much easier.", initials: "WW" },
  { id: 193, name: "Emily Walsh", role: "CDI Coordinator", location: "Manchester, UK", country: "UK", rating: 5, comment: "Perfect for CDI work! Documentation quality improved dramatically.", initials: "EW" },
  { id: 194, name: "Daniel Schmidt", role: "Medical Coder", location: "Munich, Germany", country: "Germany", rating: 3, comment: "Average platform. German healthcare system support needs work.", initials: "DS" },
  { id: 195, name: "Sophie Laurent", role: "Coding Manager", location: "Lyon, France", country: "France", rating: 5, comment: "Excellent platform! Works well with French coding standards.", initials: "SL" },
  { id: 196, name: "Lucas Santos", role: "Senior Coder", location: "Rio de Janeiro, Brazil", country: "Brazil", rating: 4, comment: "Very good tool. Portuguese language support improving.", initials: "LS" },
  { id: 197, name: "Isabella Rossi", role: "CDI Specialist", location: "Rome, Italy", country: "Italy", rating: 5, comment: "Outstanding for CDI reviews! Very comprehensive platform.", initials: "IR" },
  { id: 198, name: "Alexander Petrov", role: "Medical Coder", location: "Moscow, Russia", country: "Russia", rating: 1, comment: "Very poor. No Russian language support. Not suitable for our market.", initials: "AP" },
  { id: 199, name: "Emma Johansson", role: "Coding Specialist", location: "Stockholm, Sweden", country: "Sweden", rating: 5, comment: "Perfect tool! Works excellently with Nordic healthcare systems.", initials: "EJ" },
  { id: 200, name: "Jacob van der Berg", role: "Senior Coder", location: "Amsterdam, Netherlands", country: "Netherlands", rating: 4, comment: "Very good platform with solid performance. Recommended!", initials: "JV" },
]

// Set 3 - 100 testimonials (Different names, same distribution)
const testimonialsSet3: Testimonial[] = [
  // USA - 40 (40%)
  { id: 201, name: "Taylor Morgan", role: "Medical Coder", location: "Chicago, USA", country: "USA", rating: 5, comment: "Revolutionary platform! Changed how we approach medical coding completely.", initials: "TM" },
  { id: 202, name: "Jordan Ellis", role: "Coding Manager", location: "Los Angeles, USA", country: "USA", rating: 4, comment: "Great tool with excellent features. Minor bugs but support fixes them quickly.", initials: "JE" },
  { id: 203, name: "Casey Brooks", role: "Senior Coder", location: "New York, USA", country: "USA", rating: 5, comment: "Best coding platform on the market. Accuracy is phenomenal!", initials: "CB" },
  { id: 204, name: "Morgan Reed", role: "CDI Specialist", location: "Denver, USA", country: "USA", rating: 3, comment: "Decent platform. Works for basic needs but lacks some enterprise features.", initials: "MR" },
  { id: 205, name: "Riley Cooper", role: "Medical Coder", location: "Boston, USA", country: "USA", rating: 5, comment: "Incredible AI assistance! Makes complex coding scenarios manageable.", initials: "RC" },
  { id: 206, name: "Avery Parker", role: "Coding Specialist", location: "Seattle, USA", country: "USA", rating: 2, comment: "Too many technical issues. System lags frequently during busy hours.", initials: "AP" },
  { id: 207, name: "Quinn Bailey", role: "Senior Coder", location: "Miami, USA", country: "USA", rating: 4, comment: "Very solid platform. Search functionality is excellent.", initials: "QB" },
  { id: 208, name: "Peyton Foster", role: "CDI Coordinator", location: "Atlanta, USA", country: "USA", rating: 5, comment: "Perfect for CDI work! Documentation queries resolved quickly.", initials: "PF" },
  { id: 209, name: "Dakota Hughes", role: "Coding Director", location: "Dallas, USA", country: "USA", rating: 5, comment: "Outstanding ROI! Team productivity increased by 55%.", initials: "DH" },
  { id: 210, name: "Skylar Bennett", role: "Medical Coder", location: "Houston, USA", country: "USA", rating: 3, comment: "Average experience. Some features excellent, others need work.", initials: "SB" },
  { id: 211, name: "River Coleman", role: "Coding Manager", location: "Philadelphia, USA", country: "USA", rating: 4, comment: "Good platform for team management. Dashboard is very helpful.", initials: "RC" },
  { id: 212, name: "Phoenix Gray", role: "Senior Coder", location: "Phoenix, USA", country: "USA", rating: 5, comment: "Love this tool! Makes my job so much easier and faster.", initials: "PG" },
  { id: 213, name: "Sage Butler", role: "CDI Specialist", location: "San Antonio, USA", country: "USA", rating: 5, comment: "Best CDI platform! Quality reviews improved dramatically.", initials: "SB" },
  { id: 214, name: "Rowan Price", role: "Medical Coder", location: "San Diego, USA", country: "USA", rating: 2, comment: "Not worth the price. Better free alternatives with fewer bugs.", initials: "RP" },
  { id: 215, name: "Charlie Ross", role: "Coding Specialist", location: "San Jose, USA", country: "USA", rating: 5, comment: "Exceptional accuracy! AI suggestions are spot-on every time.", initials: "CR" },
  { id: 216, name: "Logan Perry", role: "Senior Coder", location: "Austin, USA", country: "USA", rating: 4, comment: "Very good tool. Integration options could be expanded.", initials: "LP" },
  { id: 217, name: "Parker Wood", role: "Coding Manager", location: "Jacksonville, USA", country: "USA", rating: 5, comment: "Best investment this year! Team loves the intuitive interface.", initials: "PW" },
  { id: 218, name: "Finley Sanders", role: "CDI Coordinator", location: "Fort Worth, USA", country: "USA", rating: 3, comment: "Satisfactory performance. Needs better reporting for management.", initials: "FS" },
  { id: 219, name: "Emerson James", role: "Medical Coder", location: "Columbus, USA", country: "USA", rating: 5, comment: "Perfect platform! Everything I need in one place.", initials: "EJ" },
  { id: 220, name: "Blake Watson", role: "Coding Director", location: "Charlotte, USA", country: "USA", rating: 4, comment: "Solid platform with good features. Training resources are helpful.", initials: "BW" },
  { id: 221, name: "Hayden Russell", role: "Senior Coder", location: "Indianapolis, USA", country: "USA", rating: 5, comment: "Outstanding tool! Coding accuracy improved significantly.", initials: "HR" },
  { id: 222, name: "Lennon Fisher", role: "CDI Specialist", location: "San Francisco, USA", country: "USA", rating: 1, comment: "Very frustrated. Constant crashes and lost work. Support unresponsive.", initials: "LF" },
  { id: 223, name: "Reese Henderson", role: "Medical Coder", location: "Memphis, USA", country: "USA", rating: 5, comment: "Amazing platform! Makes coding enjoyable and efficient.", initials: "RH" },
  { id: 224, name: "Sawyer Dixon", role: "Coding Specialist", location: "Detroit, USA", country: "USA", rating: 4, comment: "Very helpful for complex coding. Minor UI improvements needed.", initials: "SD" },
  { id: 225, name: "Rory Gibson", role: "Senior Coder", location: "El Paso, USA", country: "USA", rating: 5, comment: "Best coding assistant I've used! AI is incredibly intelligent.", initials: "RG" },
  { id: 226, name: "Micah Porter", role: "Coding Manager", location: "Nashville, USA", country: "USA", rating: 3, comment: "Good but not great. Waiting for promised features to be delivered.", initials: "MP" },
  { id: 227, name: "Kai Reynolds", role: "CDI Coordinator", location: "Baltimore, USA", country: "USA", rating: 5, comment: "Perfect for documentation improvement! Very comprehensive.", initials: "KR" },
  { id: 228, name: "Drew Armstrong", role: "Medical Coder", location: "Louisville, USA", country: "USA", rating: 4, comment: "Great platform with minor issues. Overall very satisfied.", initials: "DA" },
  { id: 229, name: "Quinn Spencer", role: "Coding Specialist", location: "Milwaukee, USA", country: "USA", rating: 5, comment: "Exceptional tool! Team productivity doubled since implementation.", initials: "QS" },
  { id: 230, name: "Justice Morrison", role: "Senior Coder", location: "Albuquerque, USA", country: "USA", rating: 2, comment: "Disappointed with performance. Too slow and buggy for our needs.", initials: "JM" },
  { id: 231, name: "Sutton Graham", role: "CDI Specialist", location: "Tucson, USA", country: "USA", rating: 5, comment: "Outstanding CDI tools! Makes complex reviews simple.", initials: "SG" },
  { id: 232, name: "Lennox Wells", role: "Coding Director", location: "Fresno, USA", country: "USA", rating: 4, comment: "Good ROI. Team satisfaction high and productivity improved.", initials: "LW" },
  { id: 233, name: "Marley Dixon", role: "Medical Coder", location: "Mesa, USA", country: "USA", rating: 5, comment: "Love this platform! Everything works perfectly.", initials: "MD" },
  { id: 234, name: "Sterling Bradley", role: "Coding Manager", location: "Sacramento, USA", country: "USA", rating: 3, comment: "Average tool. Some good features but missing key functionality.", initials: "SB" },
  { id: 235, name: "Ashton Owens", role: "Senior Coder", location: "Atlanta, USA", country: "USA", rating: 5, comment: "Best coding tool ever! Highly recommend to everyone.", initials: "AO" },
  { id: 236, name: "Elliott Webster", role: "CDI Coordinator", location: "Kansas City, USA", country: "USA", rating: 4, comment: "Very good platform. Documentation quality improved noticeably.", initials: "EW" },
  { id: 237, name: "Reagan Fleming", role: "Medical Coder", location: "Long Beach, USA", country: "USA", rating: 5, comment: "Perfect balance of power and ease of use. Love it!", initials: "RF" },
  { id: 238, name: "Murphy Mendoza", role: "Coding Specialist", location: "Oakland, USA", country: "USA", rating: 1, comment: "Terrible experience. Bugs everywhere and support doesn't help.", initials: "MM" },
  { id: 239, name: "Winter Norman", role: "Senior Coder", location: "Minneapolis, USA", country: "USA", rating: 5, comment: "Exceptional platform! Makes coding fun and efficient.", initials: "WN" },
  { id: 240, name: "Hollis Rice", role: "Coding Manager", location: "Tulsa, USA", country: "USA", rating: 4, comment: "Great tool for managing teams. Minor improvements would perfect it.", initials: "HR" },

  // India - 30 (30%)
  { id: 241, name: "Aryan Verma", role: "Medical Coder", location: "Mumbai, India", country: "India", rating: 5, comment: "Bahut mast platform! Coding work ekdum easy ho gaya.", initials: "AV" },
  { id: 242, name: "Aarav Sharma", role: "Senior Coder", location: "Delhi, India", country: "India", rating: 4, comment: "Very good tool. Team ko bahut pasand aaya.", initials: "AS" },
  { id: 243, name: "Anika Patel", role: "Coding Manager", location: "Bangalore, India", country: "India", rating: 5, comment: "Outstanding! Productivity badh gayi aur errors kam hui.", initials: "AP" },
  { id: 244, name: "Vihaan Kumar", role: "CDI Specialist", location: "Hyderabad, India", country: "India", rating: 3, comment: "Theek hai but pricing thoda zyada hai. Value for money better hona chahiye.", initials: "VK" },
  { id: 245, name: "Ananya Gupta", role: "Medical Coder", location: "Pune, India", country: "India", rating: 5, comment: "Perfect platform! Sab features bahut acche hai.", initials: "AG" },
  { id: 246, name: "Reyansh Singh", role: "Coding Specialist", location: "Chennai, India", country: "India", rating: 2, comment: "Not satisfied. Technical issues bohot hai. Support response slow.", initials: "RS" },
  { id: 247, name: "Isha Reddy", role: "Senior Coder", location: "Ahmedabad, India", country: "India", rating: 4, comment: "Very helpful tool. AI is smart aur accurate.", initials: "IR" },
  { id: 248, name: "Advait Joshi", role: "CDI Coordinator", location: "Surat, India", country: "India", rating: 5, comment: "Excellent CDI platform! Documentation work easy ho gaya.", initials: "AJ" },
  { id: 249, name: "Myra Desai", role: "Coding Manager", location: "Jaipur, India", country: "India", rating: 5, comment: "Best tool! Team productivity double ho gayi.", initials: "MD" },
  { id: 250, name: "Ayaan Nair", role: "Medical Coder", location: "Kochi, India", country: "India", rating: 3, comment: "Average platform. Kuch features improve karne padenge.", initials: "AN" },
  { id: 251, name: "Saanvi Iyer", role: "Coding Specialist", location: "Lucknow, India", country: "India", rating: 5, comment: "Zabardast! Coding speed badh gayi significantly.", initials: "SI" },
  { id: 252, name: "Kabir Mehta", role: "Senior Coder", location: "Nagpur, India", country: "India", rating: 4, comment: "Good platform. Customer support bhi responsive hai.", initials: "KM" },
  { id: 253, name: "Diya Pillai", role: "CDI Specialist", location: "Indore, India", country: "India", rating: 5, comment: "Perfect for CDI work! Bahut comprehensive hai.", initials: "DP" },
  { id: 254, name: "Atharv Kapoor", role: "Coding Director", location: "Bhopal, India", country: "India", rating: 2, comment: "Disappointed. Bahut bugs hai aur performance issues.", initials: "AK" },
  { id: 255, name: "Navya Shah", role: "Medical Coder", location: "Vadodara, India", country: "India", rating: 5, comment: "Excellent tool! Work ko simple bana diya.", initials: "NS" },
  { id: 256, name: "Rudra Rao", role: "Coding Manager", location: "Coimbatore, India", country: "India", rating: 4, comment: "Very good platform. Team satisfaction high hai.", initials: "RR" },
  { id: 257, name: "Kiara Bansal", role: "Senior Coder", location: "Chandigarh, India", country: "India", rating: 5, comment: "Best coding assistant! AI bahut helpful hai.", initials: "KB" },
  { id: 258, name: "Shivansh Agarwal", role: "CDI Coordinator", location: "Visakhapatnam, India", country: "India", rating: 3, comment: "Satisfactory. Kuch advanced features missing hai.", initials: "SA" },
  { id: 259, name: "Pari Kulkarni", role: "Medical Coder", location: "Nashik, India", country: "India", rating: 5, comment: "Outstanding platform! Documentation quality improve hui.", initials: "PK" },
  { id: 260, name: "Vivaan Pandey", role: "Coding Specialist", location: "Kanpur, India", country: "India", rating: 4, comment: "Great tool. Search function bahut fast hai.", initials: "VP" },
  { id: 261, name: "Aanya Deshmukh", role: "Senior Coder", location: "Aurangabad, India", country: "India", rating: 5, comment: "Perfect! Coding work enjoyable ho gaya.", initials: "AD" },
  { id: 262, name: "Shaurya Saxena", role: "CDI Specialist", location: "Gurgaon, India", country: "India", rating: 1, comment: "Very poor. System crash bohot hota hai. Support team helpful nahi.", initials: "SS" },
  { id: 263, name: "Aadhya Mishra", role: "Coding Manager", location: "Noida, India", country: "India", rating: 5, comment: "Excellent! Team ki productivity badh gayi.", initials: "AM" },
  { id: 264, name: "Arnav Tiwari", role: "Medical Coder", location: "Patna, India", country: "India", rating: 4, comment: "Very helpful platform. Minor improvements needed.", initials: "AT" },
  { id: 265, name: "Sara Bhatt", role: "Coding Specialist", location: "Rajkot, India", country: "India", rating: 5, comment: "Best tool! Sab kuch perfect hai.", initials: "SB" },
  { id: 266, name: "Dhruv Malhotra", role: "Senior Coder", location: "Agra, India", country: "India", rating: 3, comment: "Average experience. Price ke hisaab se better expected.", initials: "DM" },
  { id: 267, name: "Aarohi Chopra", role: "CDI Coordinator", location: "Meerut, India", country: "India", rating: 5, comment: "Outstanding! Documentation reviews bahut easy hui.", initials: "AC" },
  { id: 268, name: "Krishna Bhardwaj", role: "Coding Director", location: "Varanasi, India", country: "India", rating: 4, comment: "Good ROI. Team satisfaction aur productivity high.", initials: "KB" },
  { id: 269, name: "Anvi Singh", role: "Medical Coder", location: "Amritsar, India", country: "India", rating: 5, comment: "Kamaal ka platform! Work bahut easy ho gaya.", initials: "AS" },
  { id: 270, name: "Yash Kumar", role: "Senior Coder", location: "Allahabad, India", country: "India", rating: 2, comment: "Not happy. Bahut technical issues hai. Better options available.", initials: "YK" },

  // UAE - 15 (15%)
  { id: 271, name: "Amira Hassan", role: "Medical Coder", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Excellent platform! Perfect for UAE healthcare standards.", initials: "AH" },
  { id: 272, name: "Zain Ahmed", role: "Coding Manager", location: "Abu Dhabi, UAE", country: "UAE", rating: 4, comment: "Very good tool. Team productivity increased notably.", initials: "ZA" },
  { id: 273, name: "Layla Rahman", role: "CDI Specialist", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Perfect for clinical documentation. Very accurate!", initials: "LR" },
  { id: 274, name: "Hamza Al-Said", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 3, comment: "Satisfactory. Regional customization could be better.", initials: "HA" },
  { id: 275, name: "Noor Mansour", role: "Coding Specialist", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Outstanding accuracy! Best tool in Middle East.", initials: "NM" },
  { id: 276, name: "Rayan Yousef", role: "Medical Coder", location: "Ajman, UAE", country: "UAE", rating: 2, comment: "Expected better. Arabic documentation support needs work.", initials: "RY" },
  { id: 277, name: "Yasmin Zayed", role: "CDI Coordinator", location: "Dubai, UAE", country: "UAE", rating: 4, comment: "Good platform for documentation improvement work.", initials: "YZ" },
  { id: 278, name: "Khalifa Khalil", role: "Coding Director", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Excellent ROI! Team satisfaction very high.", initials: "KK" },
  { id: 279, name: "Sara Farid", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Best coding platform! Very professional and reliable.", initials: "SF" },
  { id: 280, name: "Ali Nasser", role: "Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 3, comment: "Average performance. Some features work well, others don't.", initials: "AN" },
  { id: 281, name: "Maha Ali", role: "Coding Manager", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Perfect for multi-national facilities. Very effective!", initials: "MA" },
  { id: 282, name: "Omar Saeed", role: "CDI Specialist", location: "Sharjah, UAE", country: "UAE", rating: 4, comment: "Very helpful. Documentation quality improved greatly.", initials: "OS" },
  { id: 283, name: "Hala Ibrahim", role: "Coding Specialist", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Exceptional! AI is very intelligent and accurate.", initials: "HI" },
  { id: 284, name: "Faisal Ahmad", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 1, comment: "Very poor experience. System unstable and support unhelpful.", initials: "FA" },
  { id: 285, name: "Aisha Hussein", role: "Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Outstanding! Makes coding work efficient and simple.", initials: "AH" },

  // Others - 15 (15%)
  { id: 286, name: "Jack Thompson", role: "Medical Coder", location: "Edinburgh, UK", country: "UK", rating: 5, comment: "Brilliant platform! Works perfectly with UK standards.", initials: "JT" },
  { id: 287, name: "Grace Davies", role: "Senior Coder", location: "Cardiff, UK", country: "UK", rating: 4, comment: "Very good tool. Integration could be better.", initials: "GD" },
  { id: 288, name: "Liam Campbell", role: "Coding Manager", location: "Ottawa, Canada", country: "Canada", rating: 5, comment: "Excellent for Canadian healthcare! Highly recommend.", initials: "LC" },
  { id: 289, name: "Ella Mitchell", role: "CDI Specialist", location: "Calgary, Canada", country: "Canada", rating: 3, comment: "Satisfactory. Missing some Canadian specific features.", initials: "EM" },
  { id: 290, name: "Jackson Roberts", role: "Medical Coder", location: "Brisbane, Australia", country: "Australia", rating: 5, comment: "Outstanding! Perfect for Australian coding.", initials: "JR" },
  { id: 291, name: "Ruby Anderson", role: "Senior Coder", location: "Perth, Australia", country: "Australia", rating: 2, comment: "Disappointed. Too US-focused, needs Australian support.", initials: "RA" },
  { id: 292, name: "Harry Wright", role: "Coding Specialist", location: "Cork, Ireland", country: "Ireland", rating: 4, comment: "Very helpful. Makes coding work much easier.", initials: "HW" },
  { id: 293, name: "Poppy Walsh", role: "CDI Coordinator", location: "Leeds, UK", country: "UK", rating: 5, comment: "Perfect! Documentation quality improved significantly.", initials: "PW" },
  { id: 294, name: "Felix Schmidt", role: "Medical Coder", location: "Hamburg, Germany", country: "Germany", rating: 3, comment: "Average. German healthcare support needs improvement.", initials: "FS" },
  { id: 295, name: "Amelie Laurent", role: "Coding Manager", location: "Marseille, France", country: "France", rating: 5, comment: "Excellent! Works well with French standards.", initials: "AL" },
  { id: 296, name: "Diego Santos", role: "Senior Coder", location: "Brasília, Brazil", country: "Brazil", rating: 4, comment: "Very good. Portuguese support is improving.", initials: "DS" },
  { id: 297, name: "Giulia Rossi", role: "CDI Specialist", location: "Milan, Italy", country: "Italy", rating: 5, comment: "Outstanding for CDI! Very comprehensive.", initials: "GR" },
  { id: 298, name: "Dmitri Petrov", role: "Medical Coder", location: "St Petersburg, Russia", country: "Russia", rating: 1, comment: "Very poor. No Russian support. Not suitable.", initials: "DP" },
  { id: 299, name: "Astrid Johansson", role: "Coding Specialist", location: "Gothenburg, Sweden", country: "Sweden", rating: 5, comment: "Perfect! Works excellently with Nordic systems.", initials: "AJ" },
  { id: 300, name: "Lars van der Berg", role: "Senior Coder", location: "Rotterdam, Netherlands", country: "Netherlands", rating: 4, comment: "Very good platform. Solid performance overall.", initials: "LV" },
]

// Set 4 - 100 testimonials (Different names, same distribution)
const testimonialsSet4: Testimonial[] = [
  // USA - 40 (40%)
  { id: 301, name: "Brooklyn Hayes", role: "Medical Coder", location: "Portland, USA", country: "USA", rating: 5, comment: "Game-changing platform! Revolutionized our coding workflow.", initials: "BH" },
  { id: 302, name: "Austin Crawford", role: "Coding Manager", location: "Las Vegas, USA", country: "USA", rating: 4, comment: "Great tool for managing teams. Dashboard is excellent.", initials: "AC" },
  { id: 303, name: "Savannah Pierce", role: "Senior Coder", location: "Orlando, USA", country: "USA", rating: 5, comment: "Best platform ever! Accuracy and speed are unmatched.", initials: "SP" },
  { id: 304, name: "Hunter Boyd", role: "CDI Specialist", location: "Cleveland, USA", country: "USA", rating: 3, comment: "Decent tool but missing some key enterprise features we need.", initials: "HB" },
  { id: 305, name: "Autumn Griffin", role: "Medical Coder", location: "St. Louis, USA", country: "USA", rating: 5, comment: "Incredible AI! Makes complex coding scenarios simple.", initials: "AG" },
  { id: 306, name: "Colton Murray", role: "Coding Specialist", location: "Tampa, USA", country: "USA", rating: 2, comment: "Too many bugs and performance issues. Not reliable enough.", initials: "CM" },
  { id: 307, name: "Madison Warren", role: "Senior Coder", location: "Pittsburgh, USA", country: "USA", rating: 4, comment: "Very solid platform. Search is lightning fast.", initials: "MW" },
  { id: 308, name: "Carson Stewart", role: "CDI Coordinator", location: "Cincinnati, USA", country: "USA", rating: 5, comment: "Perfect for CDI! Documentation queries resolved quickly.", initials: "CS" },
  { id: 309, name: "Violet Stone", role: "Coding Director", location: "Raleigh, USA", country: "USA", rating: 5, comment: "Outstanding ROI! Team productivity increased by 60%.", initials: "VS" },
  { id: 310, name: "Grayson Palmer", role: "Medical Coder", location: "Omaha, USA", country: "USA", rating: 3, comment: "Average tool. Some features great, others need work.", initials: "GP" },
  { id: 311, name: "Scarlett Rhodes", role: "Coding Manager", location: "Richmond, USA", country: "USA", rating: 4, comment: "Good platform. Team management features are helpful.", initials: "SR" },
  { id: 312, name: "Easton Walsh", role: "Senior Coder", location: "Oklahoma City, USA", country: "USA", rating: 5, comment: "Love it! Makes my job enjoyable and efficient.", initials: "EW" },
  { id: 313, name: "Aria Hicks", role: "CDI Specialist", location: "Hartford, USA", country: "USA", rating: 5, comment: "Best CDI platform! Quality reviews are now easy.", initials: "AH" },
  { id: 314, name: "Brayden Carr", role: "Medical Coder", location: "Buffalo, USA", country: "USA", rating: 2, comment: "Not impressed. Too expensive for what it delivers.", initials: "BC" },
  { id: 315, name: "Luna Ford", role: "Coding Specialist", location: "Reno, USA", country: "USA", rating: 5, comment: "Exceptional! AI suggestions are always accurate.", initials: "LF" },
  { id: 316, name: "Wyatt Tucker", role: "Senior Coder", location: "Providence, USA", country: "USA", rating: 4, comment: "Very good tool. Minor improvements would make it perfect.", initials: "WT" },
  { id: 317, name: "Hazel Hunt", role: "Coding Manager", location: "Worcester, USA", country: "USA", rating: 5, comment: "Best investment! Team loves the interface.", initials: "HH" },
  { id: 318, name: "Jaxon Riley", role: "CDI Coordinator", location: "Springfield, USA", country: "USA", rating: 3, comment: "Satisfactory. Needs better reporting for executives.", initials: "JR" },
  { id: 319, name: "Ivy Patterson", role: "Medical Coder", location: "Salt Lake City, USA", country: "USA", rating: 5, comment: "Perfect! Everything I need in one platform.", initials: "IP" },
  { id: 320, name: "Hudson Long", role: "Coding Director", location: "Grand Rapids, USA", country: "USA", rating: 4, comment: "Solid platform. Training resources are excellent.", initials: "HL" },
  { id: 321, name: "Willow Fisher", role: "Senior Coder", location: "Dayton, USA", country: "USA", rating: 5, comment: "Outstanding! Coding accuracy improved dramatically.", initials: "WF" },
  { id: 322, name: "Maverick Hughes", role: "CDI Specialist", location: "Des Moines, USA", country: "USA", rating: 1, comment: "Terrible. System crashes constantly. Support doesn't help.", initials: "MH" },
  { id: 323, name: "Nova Ward", role: "Medical Coder", location: "Madison, USA", country: "USA", rating: 5, comment: "Amazing! Makes coding fun and efficient.", initials: "NW" },
  { id: 324, name: "Greyson Burns", role: "Coding Specialist", location: "Little Rock, USA", country: "USA", rating: 4, comment: "Very helpful. UI could use minor improvements.", initials: "GB" },
  { id: 325, name: "Aurora Ellis", role: "Senior Coder", location: "Boise, USA", country: "USA", rating: 5, comment: "Best tool! AI is incredibly intelligent.", initials: "AE" },
  { id: 326, name: "Knox Hamilton", role: "Coding Manager", location: "Charleston, USA", country: "USA", rating: 3, comment: "Good but not great. Missing some key features.", initials: "KH" },
  { id: 327, name: "Stella Jordan", role: "CDI Coordinator", location: "Fargo, USA", country: "USA", rating: 5, comment: "Perfect! Documentation improvement is easy now.", initials: "SJ" },
  { id: 328, name: "Ezra Stone", role: "Medical Coder", location: "Sioux Falls, USA", country: "USA", rating: 4, comment: "Great platform. Minor issues but overall satisfied.", initials: "ES" },
  { id: 329, name: "Ellie Bryant", role: "Coding Specialist", location: "Anchorage, USA", country: "USA", rating: 5, comment: "Exceptional! Team productivity doubled.", initials: "EB" },
  { id: 330, name: "Bentley Fox", role: "Senior Coder", location: "Honolulu, USA", country: "USA", rating: 2, comment: "Disappointed. Performance too slow for our volume.", initials: "BF" },
  { id: 331, name: "Paisley Mason", role: "CDI Specialist", location: "Portland, USA", country: "USA", rating: 5, comment: "Outstanding CDI tools! Very comprehensive.", initials: "PM" },
  { id: 332, name: "Axel Gomez", role: "Coding Director", location: "Seattle, USA", country: "USA", rating: 4, comment: "Good ROI. Team satisfaction is high.", initials: "AG" },
  { id: 333, name: "Ruby Cooper", role: "Medical Coder", location: "Denver, USA", country: "USA", rating: 5, comment: "Love it! Everything works perfectly.", initials: "RC" },
  { id: 334, name: "Ace Reynolds", role: "Coding Manager", location: "Boston, USA", country: "USA", rating: 3, comment: "Average. Some features excellent, others lacking.", initials: "AR" },
  { id: 335, name: "Cora Sullivan", role: "Senior Coder", location: "Miami, USA", country: "USA", rating: 5, comment: "Best coding tool! Highly recommend.", initials: "CS" },
  { id: 336, name: "Cruz Morrison", role: "CDI Coordinator", location: "Atlanta, USA", country: "USA", rating: 4, comment: "Very good. Documentation reviews much easier.", initials: "CM" },
  { id: 337, name: "Penelope Ward", role: "Medical Coder", location: "Dallas, USA", country: "USA", rating: 5, comment: "Perfect! Makes my job so much easier.", initials: "PW" },
  { id: 338, name: "Declan Foster", role: "Coding Specialist", location: "Houston, USA", country: "USA", rating: 1, comment: "Awful. Bugs everywhere and no fix in sight.", initials: "DF" },
  { id: 339, name: "Magnolia Price", role: "Senior Coder", location: "Philadelphia, USA", country: "USA", rating: 5, comment: "Exceptional! Coding is now enjoyable.", initials: "MP" },
  { id: 340, name: "Knox Murphy", role: "Coding Manager", location: "Phoenix, USA", country: "USA", rating: 4, comment: "Great tool. Minor tweaks would make it flawless.", initials: "KM" },

  // India - 30 (30%)
  { id: 341, name: "Aditya Sharma", role: "Medical Coder", location: "Mumbai, India", country: "India", rating: 5, comment: "Ekdum mast! Best platform for Indian coders.", initials: "AS" },
  { id: 342, name: "Siya Verma", role: "Senior Coder", location: "Delhi, India", country: "India", rating: 4, comment: "Bahut accha hai! Team ko pasand aaya.", initials: "SV" },
  { id: 343, name: "Ahaan Patel", role: "Coding Manager", location: "Bangalore, India", country: "India", rating: 5, comment: "Outstanding! Productivity badh gayi significantly.", initials: "AP" },
  { id: 344, name: "Zara Kumar", role: "CDI Specialist", location: "Hyderabad, India", country: "India", rating: 3, comment: "Theek hai. Pricing thoda high but features acche hai.", initials: "ZK" },
  { id: 345, name: "Veer Gupta", role: "Medical Coder", location: "Pune, India", country: "India", rating: 5, comment: "Perfect! Sab features kamaal ke hai.", initials: "VG" },
  { id: 346, name: "Anaya Singh", role: "Coding Specialist", location: "Chennai, India", country: "India", rating: 2, comment: "Not good. Technical issues bohot hai. Support slow.", initials: "AS" },
  { id: 347, name: "Rohan Reddy", role: "Senior Coder", location: "Ahmedabad, India", country: "India", rating: 4, comment: "Very helpful. AI smart aur accurate hai.", initials: "RR" },
  { id: 348, name: "Aara Joshi", role: "CDI Coordinator", location: "Surat, India", country: "India", rating: 5, comment: "Excellent! Documentation work easy ho gaya.", initials: "AJ" },
  { id: 349, name: "Arjun Desai", role: "Coding Manager", location: "Jaipur, India", country: "India", rating: 5, comment: "Best tool! Team productivity double hui.", initials: "AD" },
  { id: 350, name: "Avni Nair", role: "Medical Coder", location: "Kochi, India", country: "India", rating: 3, comment: "Average. Kuch features improve karne padenge.", initials: "AN" },
  { id: 351, name: "Aryan Iyer", role: "Coding Specialist", location: "Lucknow, India", country: "India", rating: 5, comment: "Zabardast! Speed aur accuracy dono perfect.", initials: "AI" },
  { id: 352, name: "Nyra Mehta", role: "Senior Coder", location: "Nagpur, India", country: "India", rating: 4, comment: "Good platform. Support responsive hai.", initials: "NM" },
  { id: 353, name: "Shiv Pillai", role: "CDI Specialist", location: "Indore, India", country: "India", rating: 5, comment: "Perfect! CDI work bahut comprehensive hai.", initials: "SP" },
  { id: 354, name: "Ira Kapoor", role: "Coding Director", location: "Bhopal, India", country: "India", rating: 2, comment: "Disappointed. Bugs aur performance issues hai.", initials: "IK" },
  { id: 355, name: "Vivaan Shah", role: "Medical Coder", location: "Vadodara, India", country: "India", rating: 5, comment: "Excellent! Work simple ho gaya.", initials: "VS" },
  { id: 356, name: "Nitya Rao", role: "Coding Manager", location: "Coimbatore, India", country: "India", rating: 4, comment: "Very good. Team satisfaction high.", initials: "NR" },
  { id: 357, name: "Aayan Bansal", role: "Senior Coder", location: "Chandigarh, India", country: "India", rating: 5, comment: "Best! AI bahut helpful hai.", initials: "AB" },
  { id: 358, name: "Tara Agarwal", role: "CDI Coordinator", location: "Visakhapatnam, India", country: "India", rating: 3, comment: "Satisfactory. Advanced features missing.", initials: "TA" },
  { id: 359, name: "Aarav Kulkarni", role: "Medical Coder", location: "Nashik, India", country: "India", rating: 5, comment: "Outstanding! Documentation improve hui.", initials: "AK" },
  { id: 360, name: "Mira Pandey", role: "Coding Specialist", location: "Kanpur, India", country: "India", rating: 4, comment: "Great. Search function fast hai.", initials: "MP" },
  { id: 361, name: "Ishaan Deshmukh", role: "Senior Coder", location: "Aurangabad, India", country: "India", rating: 5, comment: "Perfect! Coding enjoyable ho gaya.", initials: "ID" },
  { id: 362, name: "Riya Saxena", role: "CDI Specialist", location: "Gurgaon, India", country: "India", rating: 1, comment: "Very poor. System crash hota hai. Support help nahi karta.", initials: "RS" },
  { id: 363, name: "Advay Mishra", role: "Coding Manager", location: "Noida, India", country: "India", rating: 5, comment: "Excellent! Productivity badh gayi.", initials: "AM" },
  { id: 364, name: "Anaya Tiwari", role: "Medical Coder", location: "Patna, India", country: "India", rating: 4, comment: "Very helpful. Minor improvements chahiye.", initials: "AT" },
  { id: 365, name: "Riaan Bhatt", role: "Coding Specialist", location: "Rajkot, India", country: "India", rating: 5, comment: "Best! Sab perfect hai.", initials: "RB" },
  { id: 366, name: "Aadhya Malhotra", role: "Senior Coder", location: "Agra, India", country: "India", rating: 3, comment: "Average. Price ke hisaab se better expected.", initials: "AM" },
  { id: 367, name: "Reyansh Chopra", role: "CDI Coordinator", location: "Meerut, India", country: "India", rating: 5, comment: "Outstanding! Reviews easy hui.", initials: "RC" },
  { id: 368, name: "Kiara Bhardwaj", role: "Coding Director", location: "Varanasi, India", country: "India", rating: 4, comment: "Good ROI. Team satisfaction high.", initials: "KB" },
  { id: 369, name: "Kabir Singh", role: "Medical Coder", location: "Amritsar, India", country: "India", rating: 5, comment: "Kamaal! Work easy ho gaya.", initials: "KS" },
  { id: 370, name: "Saanvi Kumar", role: "Senior Coder", location: "Allahabad, India", country: "India", rating: 2, comment: "Not happy. Issues bohot hai. Better options hai.", initials: "SK" },

  // UAE - 15 (15%)
  { id: 371, name: "Yusuf Hassan", role: "Medical Coder", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Excellent! Perfect for UAE healthcare.", initials: "YH" },
  { id: 372, name: "Amal Ahmed", role: "Coding Manager", location: "Abu Dhabi, UAE", country: "UAE", rating: 4, comment: "Very good. Team productivity high.", initials: "AA" },
  { id: 373, name: "Zaid Rahman", role: "CDI Specialist", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Perfect! Very accurate platform.", initials: "ZR" },
  { id: 374, name: "Sama Al-Said", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 3, comment: "Satisfactory. Regional features need work.", initials: "SA" },
  { id: 375, name: "Adam Mansour", role: "Coding Specialist", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Outstanding! Best in Middle East.", initials: "AM" },
  { id: 376, name: "Lina Yousef", role: "Medical Coder", location: "Ajman, UAE", country: "UAE", rating: 2, comment: "Expected better. Arabic support poor.", initials: "LY" },
  { id: 377, name: "Karim Zayed", role: "CDI Coordinator", location: "Dubai, UAE", country: "UAE", rating: 4, comment: "Good. Documentation work easier.", initials: "KZ" },
  { id: 378, name: "Leila Khalil", role: "Coding Director", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Excellent ROI! Very satisfied.", initials: "LK" },
  { id: 379, name: "Jad Farid", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Best platform! Professional and reliable.", initials: "JF" },
  { id: 380, name: "Dalia Nasser", role: "Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 3, comment: "Average. Some features good, others not.", initials: "DN" },
  { id: 381, name: "Rami Ali", role: "Coding Manager", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Perfect! Multi-national team loves it.", initials: "RA" },
  { id: 382, name: "Nora Saeed", role: "CDI Specialist", location: "Sharjah, UAE", country: "UAE", rating: 4, comment: "Very helpful. Quality improved.", initials: "NS" },
  { id: 383, name: "Sami Ibrahim", role: "Coding Specialist", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Exceptional! Very accurate AI.", initials: "SI" },
  { id: 384, name: "Maya Ahmad", role: "Senior Coder", location: "Dubai, UAE", country: "UAE", rating: 1, comment: "Very poor. Unstable and support bad.", initials: "MA" },
  { id: 385, name: "Fares Hussein", role: "Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "Outstanding! Efficient and simple.", initials: "FH" },

  // Others - 15 (15%)
  { id: 386, name: "George Thompson", role: "Medical Coder", location: "Glasgow, UK", country: "UK", rating: 5, comment: "Brilliant! Works perfectly with UK standards.", initials: "GT" },
  { id: 387, name: "Amelia Davies", role: "Senior Coder", location: "Bristol, UK", country: "UK", rating: 4, comment: "Very good. Integration improving.", initials: "AD" },
  { id: 388, name: "Mason Campbell", role: "Coding Manager", location: "Montreal, Canada", country: "Canada", rating: 5, comment: "Excellent! Team loves it.", initials: "MC" },
  { id: 389, name: "Harper Mitchell", role: "CDI Specialist", location: "Edmonton, Canada", country: "Canada", rating: 3, comment: "Satisfactory. Missing provincial features.", initials: "HM" },
  { id: 390, name: "Leo Roberts", role: "Medical Coder", location: "Adelaide, Australia", country: "Australia", rating: 5, comment: "Outstanding! Perfect for Australia.", initials: "LR" },
  { id: 391, name: "Isla Anderson", role: "Senior Coder", location: "Canberra, Australia", country: "Australia", rating: 2, comment: "Disappointed. Too US-focused.", initials: "IA" },
  { id: 392, name: "Henry Wright", role: "Coding Specialist", location: "Belfast, UK", country: "UK", rating: 4, comment: "Very helpful. Makes work easier.", initials: "HW" },
  { id: 393, name: "Freya Walsh", role: "CDI Coordinator", location: "Liverpool, UK", country: "UK", rating: 5, comment: "Perfect! Quality improved greatly.", initials: "FW" },
  { id: 394, name: "Maximilian Schmidt", role: "Medical Coder", location: "Frankfurt, Germany", country: "Germany", rating: 3, comment: "Average. German support needs work.", initials: "MS" },
  { id: 395, name: "Chloé Laurent", role: "Coding Manager", location: "Nice, France", country: "France", rating: 5, comment: "Excellent! Works well.", initials: "CL" },
  { id: 396, name: "Mateo Santos", role: "Senior Coder", location: "Porto Alegre, Brazil", country: "Brazil", rating: 4, comment: "Very good. Portuguese improving.", initials: "MS" },
  { id: 397, name: "Sofia Rossi", role: "CDI Specialist", location: "Naples, Italy", country: "Italy", rating: 5, comment: "Outstanding! Very comprehensive.", initials: "SR" },
  { id: 398, name: "Nikolai Petrov", role: "Medical Coder", location: "Novosibirsk, Russia", country: "Russia", rating: 1, comment: "Very poor. No Russian support.", initials: "NP" },
  { id: 399, name: "Linnea Johansson", role: "Coding Specialist", location: "Malmö, Sweden", country: "Sweden", rating: 5, comment: "Perfect! Works excellently.", initials: "LJ" },
  { id: 400, name: "Finn van der Berg", role: "Senior Coder", location: "Utrecht, Netherlands", country: "Netherlands", rating: 4, comment: "Very good. Solid platform.", initials: "FV" },
]

// Helper function to get a random testimonial set
export function getRandomTestimonialSet(): Testimonial[] {
  const sets = [testimonialsSet1, testimonialsSet2, testimonialsSet3, testimonialsSet4]
  const randomIndex = Math.floor(Math.random() * sets.length)
  return sets[randomIndex]
}

// Export default set for backward compatibility
export const testimonials = testimonialsSet1
