export interface Testimonial {
  id: number
  name: string
  role: string
  location: string
  country: string
  rating: number
  comment: string
  initials: string
}

export const testimonials: Testimonial[] = [
  // USA - 70 testimonials (70%)
  { id: 1, name: "Sarah Mitchell", role: "Senior Medical Coder", location: "New York, USA", country: "USA", rating: 5, comment: "AccuCoder has completely transformed my workflow. The AI assistance is incredibly accurate and saves me hours every day.", initials: "SM" },
  { id: 2, name: "Michael Thompson", role: "Coding Supervisor", location: "California, USA", country: "USA", rating: 5, comment: "Our team's productivity has increased by 40% since implementing AccuCoder. The learning resources are exceptional.", initials: "MT" },
  { id: 3, name: "Lisa Patterson", role: "CDI Specialist", location: "Texas, USA", country: "USA", rating: 5, comment: "The CDI tools are outstanding! Quick validation and compliance checking make my job so much easier.", initials: "LP" },
  { id: 4, name: "Robert Chen", role: "Medical Coder", location: "Washington, USA", country: "USA", rating: 4, comment: "Great platform with excellent search functionality. Would love to see more customization options.", initials: "RC" },
  { id: 5, name: "Jennifer Williams", role: "Coding Manager", location: "Florida, USA", country: "USA", rating: 5, comment: "Best coding platform I've used in 15 years. The accuracy and speed are unmatched.", initials: "JW" },
  { id: 6, name: "David Martinez", role: "Medical Biller", location: "Illinois, USA", country: "USA", rating: 5, comment: "AccuCoder reduced our claim denials by 35%. Absolutely worth the investment.", initials: "DM" },
  { id: 7, name: "Amanda Johnson", role: "Senior Coder", location: "Georgia, USA", country: "USA", rating: 4, comment: "Very intuitive interface. The AI assistant understands complex coding scenarios really well.", initials: "AJ" },
  { id: 8, name: "Christopher Lee", role: "Coding Specialist", location: "North Carolina, USA", country: "USA", rating: 5, comment: "Training new coders is so much easier with AccuCoder's integrated learning modules.", initials: "CL" },
  { id: 9, name: "Emily Davis", role: "Medical Coder", location: "Ohio, USA", country: "USA", rating: 5, comment: "The instant code lookup feature is a game-changer. No more flipping through manuals!", initials: "ED" },
  { id: 10, name: "James Wilson", role: "Coding Director", location: "Pennsylvania, USA", country: "USA", rating: 5, comment: "Implemented across our entire department. ROI achieved within 3 months.", initials: "JW" },
  { id: 11, name: "Patricia Brown", role: "CDI Coordinator", location: "Michigan, USA", country: "USA", rating: 4, comment: "Excellent tool for clinical documentation improvement. Very comprehensive.", initials: "PB" },
  { id: 12, name: "Daniel Garcia", role: "Medical Coder", location: "Arizona, USA", country: "USA", rating: 5, comment: "Finally, a platform that understands the complexity of medical coding!", initials: "DG" },
  { id: 13, name: "Mary Rodriguez", role: "Coding Auditor", location: "Massachusetts, USA", country: "USA", rating: 5, comment: "Audit preparation has never been this smooth. Highly recommended.", initials: "MR" },
  { id: 14, name: "Thomas Anderson", role: "Senior Coder", location: "Virginia, USA", country: "USA", rating: 4, comment: "Great platform with room for improvement in mobile accessibility.", initials: "TA" },
  { id: 15, name: "Nancy White", role: "Coding Manager", location: "Indiana, USA", country: "USA", rating: 5, comment: "Our coding accuracy improved from 92% to 98%. Outstanding results!", initials: "NW" },
  { id: 16, name: "Kevin Taylor", role: "Medical Coder", location: "Missouri, USA", country: "USA", rating: 5, comment: "The AI never fails to amaze me with its coding suggestions. Very smart!", initials: "KT" },
  { id: 17, name: "Barbara Moore", role: "CDI Specialist", location: "Wisconsin, USA", country: "USA", rating: 5, comment: "Best investment our hospital has made in years. Everyone loves it.", initials: "BM" },
  { id: 18, name: "Steven Jackson", role: "Coding Supervisor", location: "Minnesota, USA", country: "USA", rating: 4, comment: "Solid platform with excellent customer support. Very responsive team.", initials: "SJ" },
  { id: 19, name: "Karen Martin", role: "Medical Coder", location: "Colorado, USA", country: "USA", rating: 5, comment: "Makes coding so much faster and more accurate. Can't imagine working without it.", initials: "KM" },
  { id: 20, name: "Brian Thompson", role: "Senior Coder", location: "Oregon, USA", country: "USA", rating: 5, comment: "The search functionality is incredibly fast. Saves me at least 2 hours daily.", initials: "BT" },
  { id: 21, name: "Susan Harris", role: "Coding Director", location: "Connecticut, USA", country: "USA", rating: 5, comment: "Excellent ROI and team satisfaction. Our best technology decision this year.", initials: "SH" },
  { id: 22, name: "Paul Clark", role: "Medical Coder", location: "Iowa, USA", country: "USA", rating: 4, comment: "Very helpful for complex cases. Would like to see more tutorial videos.", initials: "PC" },
  { id: 23, name: "Dorothy Lewis", role: "CDI Nurse", location: "Nevada, USA", country: "USA", rating: 5, comment: "Perfect blend of clinical and coding knowledge. Extremely valuable.", initials: "DL" },
  { id: 24, name: "Mark Robinson", role: "Coding Specialist", location: "Utah, USA", country: "USA", rating: 5, comment: "AccuCoder helps me stay updated with the latest coding guidelines effortlessly.", initials: "MR" },
  { id: 25, name: "Helen Walker", role: "Medical Coder", location: "Nebraska, USA", country: "USA", rating: 5, comment: "Outstanding accuracy and user-friendly interface. Highly recommend!", initials: "HW" },
  { id: 26, name: "George Hall", role: "Coding Manager", location: "Kansas, USA", country: "USA", rating: 4, comment: "Great tool overall. Minor bugs but support team fixes them quickly.", initials: "GH" },
  { id: 27, name: "Betty Allen", role: "Senior Coder", location: "Louisiana, USA", country: "USA", rating: 5, comment: "The best coding platform on the market. Period.", initials: "BA" },
  { id: 28, name: "Kenneth Young", role: "Medical Coder", location: "South Carolina, USA", country: "USA", rating: 5, comment: "AccuCoder makes complex coding scenarios manageable and straightforward.", initials: "KY" },
  { id: 29, name: "Sandra King", role: "CDI Specialist", location: "Alabama, USA", country: "USA", rating: 5, comment: "Incredible platform! Our documentation quality has improved significantly.", initials: "SK" },
  { id: 30, name: "Edward Wright", role: "Coding Supervisor", location: "Kentucky, USA", country: "USA", rating: 4, comment: "Very efficient and reliable. Training new staff is much easier now.", initials: "EW" },
  { id: 31, name: "Margaret Scott", role: "Medical Coder", location: "Oklahoma, USA", country: "USA", rating: 5, comment: "Finally found a coding tool that actually understands what coders need!", initials: "MS" },
  { id: 32, name: "Jason Green", role: "Senior Coder", location: "Arkansas, USA", country: "USA", rating: 5, comment: "The AI suggestions are spot-on. Rarely need to make corrections.", initials: "JG" },
  { id: 33, name: "Donna Baker", role: "Coding Director", location: "Mississippi, USA", country: "USA", rating: 5, comment: "Best decision for our coding department. Results speak for themselves.", initials: "DB" },
  { id: 34, name: "Raymond Adams", role: "Medical Coder", location: "New Mexico, USA", country: "USA", rating: 4, comment: "Very good platform. Would appreciate more keyboard shortcuts.", initials: "RA" },
  { id: 35, name: "Carol Nelson", role: "CDI Coordinator", location: "West Virginia, USA", country: "USA", rating: 5, comment: "Exceptional quality and reliability. Our go-to coding solution.", initials: "CN" },
  { id: 36, name: "Frank Carter", role: "Coding Specialist", location: "Montana, USA", country: "USA", rating: 5, comment: "AccuCoder is incredibly intuitive. New coders love how easy it is.", initials: "FC" },
  { id: 37, name: "Ruth Mitchell", role: "Medical Coder", location: "Delaware, USA", country: "USA", rating: 5, comment: "The platform has exceeded all my expectations. Truly remarkable!", initials: "RM" },
  { id: 38, name: "Jeffrey Perez", role: "Senior Coder", location: "South Dakota, USA", country: "USA", rating: 4, comment: "Great features and solid performance. Looking forward to new updates.", initials: "JP" },
  { id: 39, name: "Michelle Roberts", role: "Coding Manager", location: "Alaska, USA", country: "USA", rating: 5, comment: "Our team productivity increased dramatically. Best tool investment ever.", initials: "MR" },
  { id: 40, name: "Gary Turner", role: "Medical Coder", location: "Vermont, USA", country: "USA", rating: 5, comment: "AccuCoder makes coding enjoyable. Never thought I'd say that!", initials: "GT" },
  { id: 41, name: "Laura Phillips", role: "CDI Specialist", location: "Wyoming, USA", country: "USA", rating: 5, comment: "Perfect for CDI work. Comprehensive and very accurate.", initials: "LP" },
  { id: 42, name: "Larry Campbell", role: "Coding Supervisor", location: "Hawaii, USA", country: "USA", rating: 5, comment: "Excellent platform with outstanding support team. Very satisfied.", initials: "LC" },
  { id: 43, name: "Sharon Parker", role: "Medical Coder", location: "Rhode Island, USA", country: "USA", rating: 4, comment: "Very helpful and efficient. Minor improvements needed in reporting.", initials: "SP" },
  { id: 44, name: "Dennis Evans", role: "Senior Coder", location: "Maine, USA", country: "USA", rating: 5, comment: "The learning curve is minimal. Started being productive immediately.", initials: "DE" },
  { id: 45, name: "Kimberly Edwards", role: "Coding Director", location: "New Hampshire, USA", country: "USA", rating: 5, comment: "Transformed our entire coding operation. Couldn't be happier!", initials: "KE" },
  { id: 46, name: "Ronald Collins", role: "Medical Coder", location: "Idaho, USA", country: "USA", rating: 5, comment: "AccuCoder is the future of medical coding. Absolutely brilliant!", initials: "RC" },
  { id: 47, name: "Cynthia Stewart", role: "CDI Nurse", location: "New York, USA", country: "USA", rating: 5, comment: "Clinical accuracy combined with coding expertise. Perfect combination!", initials: "CS" },
  { id: 48, name: "Eric Morris", role: "Coding Specialist", location: "California, USA", country: "USA", rating: 4, comment: "Very good platform. Integration with our EHR could be smoother.", initials: "EM" },
  { id: 49, name: "Deborah Rogers", role: "Medical Coder", location: "Texas, USA", country: "USA", rating: 5, comment: "The best coding tool I've used in my 20-year career.", initials: "DR" },
  { id: 50, name: "Scott Reed", role: "Senior Coder", location: "Florida, USA", country: "USA", rating: 5, comment: "Efficiency and accuracy in one package. Highly recommend AccuCoder!", initials: "SR" },
  { id: 51, name: "Angela Cook", role: "Coding Manager", location: "Illinois, USA", country: "USA", rating: 5, comment: "Our coding quality metrics have never been better. Excellent tool!", initials: "AC" },
  { id: 52, name: "Timothy Morgan", role: "Medical Coder", location: "Georgia, USA", country: "USA", rating: 4, comment: "Very reliable and fast. Would like more customization options.", initials: "TM" },
  { id: 53, name: "Brenda Bell", role: "CDI Specialist", location: "North Carolina, USA", country: "USA", rating: 5, comment: "Outstanding for CDI reviews. Makes my job so much easier!", initials: "BB" },
  { id: 54, name: "Patrick Murphy", role: "Coding Supervisor", location: "Ohio, USA", country: "USA", rating: 5, comment: "Team loves it! Productivity up, errors down. Perfect results.", initials: "PM" },
  { id: 55, name: "Carolyn Bailey", role: "Medical Coder", location: "Pennsylvania, USA", country: "USA", rating: 5, comment: "AccuCoder saves me time and reduces stress. Fantastic platform!", initials: "CB" },
  { id: 56, name: "Harold Rivera", role: "Senior Coder", location: "Michigan, USA", country: "USA", rating: 4, comment: "Solid coding tool with excellent search capabilities.", initials: "HR" },
  { id: 57, name: "Janet Cooper", role: "Coding Director", location: "Arizona, USA", country: "USA", rating: 5, comment: "Best investment for our coding department. ROI in weeks, not months!", initials: "JC" },
  { id: 58, name: "Willie Richardson", role: "Medical Coder", location: "Massachusetts, USA", country: "USA", rating: 5, comment: "The AI is incredibly smart and helpful. Love this tool!", initials: "WR" },
  { id: 59, name: "Joyce Cox", role: "CDI Coordinator", location: "Virginia, USA", country: "USA", rating: 5, comment: "Perfect for comprehensive documentation improvement initiatives.", initials: "JC" },
  { id: 60, name: "Gerald Howard", role: "Coding Specialist", location: "Indiana, USA", country: "USA", rating: 5, comment: "AccuCoder makes complex coding simple. Brilliant design!", initials: "GH" },
  { id: 61, name: "Theresa Ward", role: "Medical Coder", location: "Missouri, USA", country: "USA", rating: 4, comment: "Great tool overall. Some minor features still in development.", initials: "TW" },
  { id: 62, name: "Carl Torres", role: "Senior Coder", location: "Wisconsin, USA", country: "USA", rating: 5, comment: "The speed and accuracy are unmatched. Absolutely love it!", initials: "CT" },
  { id: 63, name: "Evelyn Peterson", role: "Coding Manager", location: "Minnesota, USA", country: "USA", rating: 5, comment: "Our team's efficiency increased by 45%. Remarkable results!", initials: "EP" },
  { id: 64, name: "Arthur Gray", role: "Medical Coder", location: "Colorado, USA", country: "USA", rating: 5, comment: "AccuCoder is intuitive, powerful, and incredibly reliable.", initials: "AG" },
  { id: 65, name: "Jacqueline Ramirez", role: "CDI Specialist", location: "Oregon, USA", country: "USA", rating: 5, comment: "Best CDI tool available. Comprehensive and user-friendly.", initials: "JR" },
  { id: 66, name: "Russell James", role: "Coding Supervisor", location: "Connecticut, USA", country: "USA", rating: 4, comment: "Very effective platform. Support team is excellent.", initials: "RJ" },
  { id: 67, name: "Gloria Watson", role: "Medical Coder", location: "Iowa, USA", country: "USA", rating: 5, comment: "Makes my daily coding tasks effortless. Couldn't work without it!", initials: "GW" },
  { id: 68, name: "Henry Brooks", role: "Senior Coder", location: "Nevada, USA", country: "USA", rating: 5, comment: "The best coding assistant I've ever used. Truly exceptional!", initials: "HB" },
  { id: 69, name: "Teresa Kelly", role: "Coding Director", location: "Utah, USA", country: "USA", rating: 5, comment: "Transformed our coding operation completely. Outstanding platform!", initials: "TK" },
  { id: 70, name: "Douglas Sanders", role: "Medical Coder", location: "Nebraska, USA", country: "USA", rating: 5, comment: "AccuCoder is reliable, fast, and incredibly accurate. Love it!", initials: "DS" },

  // India - 25 testimonials (25%)
  { id: 71, name: "Priya Sharma", role: "Medical Coding Specialist", location: "Mumbai, India", country: "India", rating: 5, comment: "AccuCoder is simply amazing! It has made coding so much easier and faster. Best tool for Indian coders.", initials: "PS" },
  { id: 72, name: "Rajesh Kumar", role: "Senior Medical Coder", location: "Bangalore, India", country: "India", rating: 5, comment: "Bahut accha platform hai! The AI is very intelligent and understands complex cases perfectly.", initials: "RK" },
  { id: 73, name: "Anjali Patel", role: "Coding Team Lead", location: "Pune, India", country: "India", rating: 4, comment: "Great tool for our team. Productivity badh gaya significantly. Would recommend to everyone!", initials: "AP" },
  { id: 74, name: "Vikram Singh", role: "Medical Coder", location: "Hyderabad, India", country: "India", rating: 5, comment: "Perfect platform for medical coding. Training naye coders ko is very easy now. Excellent!", initials: "VS" },
  { id: 75, name: "Deepika Reddy", role: "CDI Specialist", location: "Chennai, India", country: "India", rating: 5, comment: "Outstanding tool! Our accuracy has improved tremendously. Best investment for our department.", initials: "DR" },
  { id: 76, name: "Amit Verma", role: "Coding Supervisor", location: "Delhi, India", country: "India", rating: 5, comment: "Ekdum mast hai! The search speed is incredible. Our team loves AccuCoder.", initials: "AV" },
  { id: 77, name: "Sneha Joshi", role: "Medical Coder", location: "Ahmedabad, India", country: "India", rating: 4, comment: "Very helpful for daily coding. Kuch minor improvements needed but overall fantastic platform.", initials: "SJ" },
  { id: 78, name: "Arjun Nair", role: "Senior Coder", location: "Kochi, India", country: "India", rating: 5, comment: "AccuCoder has changed the game for us. Speed aur accuracy dono perfect hai!", initials: "AN" },
  { id: 79, name: "Kavita Desai", role: "Coding Manager", location: "Surat, India", country: "India", rating: 5, comment: "Our coding department's performance improved by 40%. Highly recommend this platform!", initials: "KD" },
  { id: 80, name: "Rahul Gupta", role: "Medical Coder", location: "Jaipur, India", country: "India", rating: 5, comment: "Bahut helpful hai! Makes complex coding simple. Best tool for medical coders in India.", initials: "RG" },
  { id: 81, name: "Pooja Iyer", role: "CDI Coordinator", location: "Bangalore, India", country: "India", rating: 5, comment: "Excellent platform with amazing features. CDI work has become so much easier!", initials: "PI" },
  { id: 82, name: "Sanjay Mehta", role: "Coding Specialist", location: "Mumbai, India", country: "India", rating: 4, comment: "Very good platform. User-friendly interface aur fast search. Great for our team.", initials: "SM" },
  { id: 83, name: "Meera Rao", role: "Medical Coder", location: "Pune, India", country: "India", rating: 5, comment: "Best coding assistant ever! AI is super smart and helpful. Highly recommended!", initials: "MR" },
  { id: 84, name: "Karthik Pillai", role: "Senior Coder", location: "Hyderabad, India", country: "India", rating: 5, comment: "Outstanding accuracy and speed. Our team's productivity badh gaya exponentially!", initials: "KP" },
  { id: 85, name: "Divya Shah", role: "Coding Team Lead", location: "Chennai, India", country: "India", rating: 5, comment: "Perfect tool for managing coding team. Everyone loves it. Bahut sahi hai!", initials: "DS" },
  { id: 86, name: "Manish Jain", role: "Medical Coder", location: "Delhi, India", country: "India", rating: 4, comment: "Very helpful and efficient. Some features mein improvement chahiye but overall excellent.", initials: "MJ" },
  { id: 87, name: "Shruti Kulkarni", role: "CDI Specialist", location: "Ahmedabad, India", country: "India", rating: 5, comment: "AccuCoder is a game-changer! Documentation quality has improved significantly.", initials: "SK" },
  { id: 88, name: "Aditya Bhatt", role: "Coding Supervisor", location: "Kochi, India", country: "India", rating: 5, comment: "Excellent platform with great support. Our coding accuracy is now 98%!", initials: "AB" },
  { id: 89, name: "Neha Malhotra", role: "Medical Coder", location: "Surat, India", country: "India", rating: 5, comment: "Best investment for our company! Time save hota hai aur accuracy bhi improve hui.", initials: "NM" },
  { id: 90, name: "Varun Kapoor", role: "Senior Coder", location: "Jaipur, India", country: "India", rating: 5, comment: "AccuCoder is simply the best! Fast, accurate, and very user-friendly. Love it!", initials: "VK" },
  { id: 91, name: "Ritika Saxena", role: "Coding Manager", location: "Bangalore, India", country: "India", rating: 5, comment: "Outstanding results for our team. Productivity aur accuracy both improved dramatically!", initials: "RS" },
  { id: 92, name: "Nikhil Agarwal", role: "Medical Coder", location: "Mumbai, India", country: "India", rating: 4, comment: "Very good platform. AI assistance is top-notch. Kuch features ko aur better banao.", initials: "NA" },
  { id: 93, name: "Ishita Bansal", role: "CDI Specialist", location: "Pune, India", country: "India", rating: 5, comment: "Perfect for CDI work! Makes documentation review so much easier and faster.", initials: "IB" },
  { id: 94, name: "Rohan Chopra", role: "Coding Specialist", location: "Hyderabad, India", country: "India", rating: 5, comment: "AccuCoder is amazing! Coding speed badh gaya and errors kam ho gaye. Highly recommend!", initials: "RC" },
  { id: 95, name: "Sakshi Pandey", role: "Medical Coder", location: "Chennai, India", country: "India", rating: 5, comment: "Best coding platform available! Easy to use aur very accurate. Love AccuCoder!", initials: "SP" },

  // Dubai & Other Countries - 5 testimonials (5%)
  { id: 96, name: "Ahmed Al-Rashid", role: "Medical Coding Manager", location: "Dubai, UAE", country: "UAE", rating: 5, comment: "Excellent platform for our healthcare facility. The accuracy and speed are outstanding!", initials: "AA" },
  { id: 97, name: "Fatima Hassan", role: "Senior Medical Coder", location: "Abu Dhabi, UAE", country: "UAE", rating: 5, comment: "AccuCoder has transformed our coding department. Best tool in the Middle East market!", initials: "FH" },
  { id: 98, name: "Mohammed Khan", role: "CDI Specialist", location: "Dubai, UAE", country: "UAE", rating: 4, comment: "Very efficient and reliable platform. Great for multi-national healthcare facilities.", initials: "MK" },
  { id: 99, name: "Sarah Al-Mansoori", role: "Coding Supervisor", location: "Sharjah, UAE", country: "UAE", rating: 5, comment: "Outstanding quality and support! Our team productivity increased significantly.", initials: "SA" },
  { id: 100, name: "David O'Connor", role: "Medical Coder", location: "London, UK", country: "UK", rating: 5, comment: "Brilliant platform! Works perfectly for international medical coding standards. Highly recommended!", initials: "DO" },
]
